; Symbol- und Property-List-lastiger Heap-Workload fuer
; tools/host-lisp/compact-model.py (--heap-profile).
; Im Unterschied zum ersten Versuch enthaelt der erreichbare Graph bewusst
; CONS-Payloads. So bleibt der Mix symbol-/plist-betont, misst aber trotzdem die
; relevante Cons-Layout-Frage.

; --- Hilfsfunktionen (Kern-Dialekt) ---
(DE HP-ITEMS (N TAG ACC)
  (COND ((ZEROP N) ACC)
        (T (HP-ITEMS (SUB1 N)
                     TAG
                     (CONS (CONS TAG (CONS N (CONS 'VALUE (CONS N NIL))))
                           ACC)))))

(DE HP-CHAIN (N NEXT ACC)
  (COND ((ZEROP N) ACC)
        (T (HP-CHAIN (SUB1 N)
                     NEXT
                     (CONS (CONS 'LINK (CONS N (CONS NEXT NIL))) ACC)))))

(DE HP-SET-SYMBOL-PLIST (SYM ROLE NEIGHBOR REVERSE PAYLOAD CHAIN NAME)
  (PUTPROP SYM 'ROLE ROLE)
  (PUTPROP SYM 'NEIGHBOR NEIGHBOR)
  (PUTPROP SYM 'REVERSE REVERSE)
  (PUTPROP SYM 'PAYLOAD PAYLOAD)
  (PUTPROP SYM 'CHAIN CHAIN)
  (PUTPROP SYM 'NAME NAME)
  SYM)

; --- Cons-haltige Nutzdaten ---
(SETQ HP-PAYLOAD-A (HP-ITEMS 18 'PA NIL))
(SETQ HP-PAYLOAD-B (HP-ITEMS 18 'PB NIL))
(SETQ HP-PAYLOAD-C (HP-ITEMS 18 'PC NIL))
(SETQ HP-PAYLOAD-D (HP-ITEMS 18 'PD NIL))
(SETQ HP-PAYLOAD-E (HP-ITEMS 18 'PE NIL))
(SETQ HP-PAYLOAD-F (HP-ITEMS 18 'PF NIL))

(SETQ HP-CHAIN-A (HP-CHAIN 10 'HP-SYM-B NIL))
(SETQ HP-CHAIN-B (HP-CHAIN 10 'HP-SYM-C NIL))
(SETQ HP-CHAIN-C (HP-CHAIN 10 'HP-SYM-D NIL))
(SETQ HP-CHAIN-D (HP-CHAIN 10 'HP-SYM-E NIL))
(SETQ HP-CHAIN-E (HP-CHAIN 10 'HP-SYM-F NIL))
(SETQ HP-CHAIN-F (HP-CHAIN 10 'HP-SYM-A NIL))

(SETQ HP-NAME-A "SYMBOL-HEAVY-PAYLOAD-A")
(SETQ HP-NAME-B "SYMBOL-HEAVY-PAYLOAD-B")
(SETQ HP-NAME-C "SYMBOL-HEAVY-PAYLOAD-C")
(SETQ HP-NAME-D "SYMBOL-HEAVY-PAYLOAD-D")
(SETQ HP-NAME-E "SYMBOL-HEAVY-PAYLOAD-E")
(SETQ HP-NAME-F "SYMBOL-HEAVY-PAYLOAD-F")

; --- Symbol-Graphen mit Property-Listen ---
(HP-SET-SYMBOL-PLIST 'HP-SYM-A 'K1 'HP-SYM-B 'HP-SYM-F HP-PAYLOAD-A HP-CHAIN-A HP-NAME-A)
(HP-SET-SYMBOL-PLIST 'HP-SYM-B 'K2 'HP-SYM-C 'HP-SYM-A HP-PAYLOAD-B HP-CHAIN-B HP-NAME-B)
(HP-SET-SYMBOL-PLIST 'HP-SYM-C 'K3 'HP-SYM-D 'HP-SYM-B HP-PAYLOAD-C HP-CHAIN-C HP-NAME-C)
(HP-SET-SYMBOL-PLIST 'HP-SYM-D 'K4 'HP-SYM-E 'HP-SYM-C HP-PAYLOAD-D HP-CHAIN-D HP-NAME-D)
(HP-SET-SYMBOL-PLIST 'HP-SYM-E 'K5 'HP-SYM-F 'HP-SYM-D HP-PAYLOAD-E HP-CHAIN-E HP-NAME-E)
(HP-SET-SYMBOL-PLIST 'HP-SYM-F 'K6 'HP-SYM-A 'HP-SYM-E HP-PAYLOAD-F HP-CHAIN-F HP-NAME-F)

(PUTPROP 'HP-ROOT 'SYMBOLS
  (LIST 'HP-SYM-A 'HP-SYM-B 'HP-SYM-C 'HP-SYM-D 'HP-SYM-E 'HP-SYM-F))
(PUTPROP 'HP-ROOT 'PRIMARY HP-PAYLOAD-A)
(PUTPROP 'HP-ROOT 'SECONDARY HP-PAYLOAD-D)
(PUTPROP 'HP-ROOT 'DESCRIPTION "SYMBOL-AND-PLIST-HEAVY-CONS-PROFILE")

; Eine einzelne Wurzel vermeidet Mehrfachzaehlung desselben geteilten Graphen im
; Host-Profiler und laesst den Collector den Symbol-/Plist-Graphen selbst folgen.
(SETQ HEAP-PROFILE-ROOTS 'HP-ROOT)
