; Hyphen-free C64 LOAD variant of the focused sequence smoke helpers.
; Internal helper names are intentionally short so each emitted SAVE-format
; property-list entry fits the C64 file-input line limit.

(DE FINDIF (P L) (F1 P L))
(DE F1 (P L)
  (COND ((NULL L) NIL)
        (T (F2 P L))))
(DE F2 (P L)
  (COND ((FUNCALL P (CAR L)) (CAR L))
        (T (F3 P L))))
(DE F3 (P L) (FINDIF P (CDR L)))

(DE SEQTAKE (N L) (T1 N L))
(DE T1 (N L)
  (COND ((ZEROP N) NIL)
        (T (T2 N L))))
(DE T2 (N L)
  (COND ((NULL L) NIL)
        (T (T3 N L))))
(DE T3 (N L) (CONS (CAR L) (SEQTAKE (SUB1 N) (CDR L))))

(DE SEQDROP (N L) (D1 N L))
(DE D1 (N L)
  (COND ((ZEROP N) L)
        (T (D2 N L))))
(DE D2 (N L)
  (COND ((NULL L) NIL)
        (T (D3 N L))))
(DE D3 (N L) (SEQDROP (SUB1 N) (CDR L)))

(DE SUBSEQ (L S E) (Q1 L S E))
(DE Q1 (L S E)
  (COND ((NULL E) (SEQDROP S L))
        (T (Q2 L S E))))
(DE Q2 (L S E) (SEQTAKE (DIFFERENCE E S) (SEQDROP S L)))

(DE SEQMEMBERP (X L) (M1 X L))
(DE M1 (X L)
  (COND ((NULL L) NIL)
        (T (M2 X L))))
(DE M2 (X L)
  (COND ((EQL X (CAR L)) T)
        (T (M3 X L))))
(DE M3 (X L) (SEQMEMBERP X (CDR L)))

(DE SEQRDAUX (L S) (R1 L S))
(DE R1 (L S)
  (COND ((NULL L) NIL)
        (T (R2 L S))))
(DE R2 (L S)
  (COND ((SEQMEMBERP (CAR L) S) (R4 L S))
        (T (R3 L S))))
(DE R3 (L S) (CONS (CAR L) (SEQRDAUX (CDR L) (CONS (CAR L) S))))
(DE R4 (L S) (SEQRDAUX (CDR L) S))
(DE REMOVEDUPS (L) (SEQRDAUX L NIL))

(DE SEQINSERT (X S P) (I1 X S P))
(DE I1 (X S P)
  (COND ((NULL S) (LIST X))
        (T (I2 X S P))))
(DE I2 (X S P)
  (COND ((I5 X S P) (I4 X S))
        (T (I3 X S P))))
(DE I3 (X S P) (CONS (CAR S) (SEQINSERT X (CDR S) P)))
(DE I4 (X S) (CONS X S))
(DE I5 (X S P) (FUNCALL P X (CAR S)))

(DE SORT (L P) (S1 L P))
(DE S1 (L P)
  (COND ((NULL L) NIL)
        (T (S2 L P))))
(DE S2 (L P) (SEQINSERT (CAR L) (SORT (CDR L) P) P))
