; C64 LOAD smoke for the full LOOP library: REPEAT, FOR IN, FOR FROM, COLLECT, SUM.
; Prerequisite: lib-loop-c64-load.lsp already loaded (defines LOOP-DISPATCH + DM LOOP).

(CHECK (LOOP REPEAT 3 COLLECT (QUOTE X)) (QUOTE (X X X)))
(CHECK (LOOP FOR X IN (QUOTE (1 2 3)) COLLECT (TIMES X X)) (QUOTE (1 4 9)))
(CHECK (LOOP FOR I FROM 1 TO 5 SUM I) 15)
(CHECK (LOOP FOR I FROM 0 TO 10 BY 2 COLLECT I) (QUOTE (0 2 4 6 8 10)))
(CHECK (LOOP FOR X IN (QUOTE (1 2 3 4)) SUM X) 10)
(CHECK (LOOP REPEAT 0 COLLECT (QUOTE A)) NIL)

(CHECKREPORT)
