; C64-LOAD-sichere Ergaenzung fuer platform-demo.lsp.
; Bindestrichfreie Einstiege vermeiden Reader-/Dispatch-Kanten im echten LOAD-Pfad.

(DE LINEGRAPH (POINTS COLOR) (LG1 POINTS COLOR))
(DE LINE-GRAPH (POINTS COLOR) (LINEGRAPH POINTS COLOR))
(DE LG1 (POINTS COLOR)
  (COND ((NULL POINTS) NIL) (T (LG2 POINTS COLOR))))
(DE LG2 (POINTS COLOR)
  (COND ((NULL (CDR POINTS)) T) (T (LG3 POINTS COLOR))))
(DE LG3 (POINTS COLOR)
  (LG4 POINTS COLOR (DLPT (CAR POINTS) (CAR (CDR POINTS)) COLOR)))
(DE LG4 (POINTS COLOR R)
  (LINEGRAPH (CDR POINTS) COLOR))
(DE DLPT (A B COLOR) (DRAWLINE (CAR A) (CDR A) (CAR B) (CDR B) COLOR))

(DE PDBAR (BX H YBASE W COLOR)
  (FILLRECTANGLE BX (DIFFERENCE YBASE H) (PLUS BX (SUB1 W)) YBASE COLOR))
(DE PDBARS (HS I X0 YBASE W COLOR)
  (COND ((NULL HS) T) (T (PDBARS1 HS I X0 YBASE W COLOR
    (PDBAR (PLUS X0 (TIMES I (ADD1 W))) (CAR HS) YBASE W COLOR)))))
(DE PDBARS1 (HS I X0 YBASE W COLOR R)
  (PDBARS (CDR HS) (ADD1 I) X0 YBASE W COLOR))
(DE DRAWBARS (HEIGHTS X0 YBASE W COLOR) (PDBARS HEIGHTS 0 X0 YBASE W COLOR))

(DE DEMODASH () (DD1 (CLEARSCREEN 0)))
(DE DD1 (R) (DD2 (DRAWRECTANGLE 0 0 15 9 1)))
(DE DD2 (R) (DD3 (FILLRECTANGLE 1 1 14 1 2)))
(DE DD3 (R) (DD4 (DRAWBARS '(2 4 1 3) 2 8 1 7)))
(DE DD4 (R) (LINEGRAPH '((1 . 7) (5 . 5) (9 . 6) (13 . 3)) 5))
(DE DEMO-DASHBOARD () (DEMODASH))
