(* VICE CROSSCHECK LISP 64 DIALEKT TREUE)
(* siehe docs vice-crosscheck punkt md)
(* nutzt nur native primitive kommentar form stern)
(SETQ PV 0)
(SETQ FV 0)
(DE CK (G E)(COND((EQUAL G E)(SETQ PV(ADD1 PV)))(T(SETQ FV(ADD1 FV)))))
(* basics)
(CK (CAR '(A B C)) 'A)
(CK (CDR '(A B C)) '(B C))
(CK (CONS 'A '(B)) '(A B))
(CK (REVERSE '(A B C)) '(C B A))
(CK (APPEND '(A) '(B)) '(A B))
(CK (LENGTH '(A B C)) 3)
(* arithmetik)
(CK (PLUS 1 2 3) 6)
(CK (TIMES 4 5) 20)
(CK (DIFFERENCE 10 3) 7)
(CK (QUOTIENT 17 5) 3)
(CK (REMAINDER 17 5) 2)
(CK (LESSP 2 3) T)
(CK (GREATERP 2 3) NIL)
(CK (ADD1 9) 10)
(* gleichheit)
(CK (EQ 4 4) T)
(CK (EQ 4 5) NIL)
(CK (EQUAL '(A (B)) '(A (B))) T)
(* dialekt eigenheiten last nth assoc member mapc remove)
(CK (LAST '(A B C)) 'C)
(CK (NTH '(A B C D) 3) '(C D))
(CK (ASSOC 'B '((A . 1)(B . 2))) '(B . 2))
(CK (MEMBER '(X) '((Y)(X)(Z))) '((X)(Z)))
(CK (NULL (MAPC 'ADD1 '(1 2))) T)
(CK (REMOVE 'A '(A B A C)) '(B C))
(CK (MAPCAR 'ADD1 '(1 2 3)) '(2 3 4))
(* false atom F und kommentar stern)
(CK (COND (F 1)(T 2)) 2)
(CK (* AA BB) NIL)
(* string symbol)
(CK (PACK '(A B C)) 'ABC)
(CK (UNPACK 'AB) '(A B))
(CK (ASC "A") 65)
(* dynamisches scoping freies X in INN)
(DE OUT (X)(INN))
(DE INN NIL (ADD1 X))
(CK (OUT 7) 8)
(* getdef rekonstruiert definitionsform)
(DE GG (N)(ADD1 N))
(CK (CONSP (GETDEF GG)) T)
(* property listen)
(PUTPROP 'AU 'YR 1982)
(CK (GETPROP 'AU 'YR) 1982)
(* report marker VICECHK pass fail)
(PRINC "VICECHK ")
(PRIN1 PV)
(PRINC " ")
(PRINT FV)
