/* generated by tools/host-lisp/bytecode_p0_stdlib.py; do not edit */
#ifndef LISP65_BYTECODE_STDLIB_P0_H
#define LISP65_BYTECODE_STDLIB_P0_H
#include <stdint.h>

#define LISP65_BC_LIT_INVALID 0
#define LISP65_BC_LIT_FIX 1
#define LISP65_BC_LIT_NIL 2
#define LISP65_BC_LIT_T 3
#define LISP65_BC_LIT_SYMBOL 4
#define LISP65_BC_LIT_CONS 5
#define LISP65_BC_LIT_LIST 6
#define LISP65_BC_LIT_STRING 7
#define LISP65_BC_LIT_ENTRY_REF 8

#define LISP65_BC_ENTRY_MACRO 1

#define LISP65_BYTECODE_STDLIB_BASE_ADDR 0x050000u
#define LISP65_BYTECODE_STDLIB_OBJECT_COUNT 398u
#define LISP65_BYTECODE_STDLIB_EMBED_COUNT 398u
#define LISP65_BYTECODE_STDLIB_BLOB_BYTES 18664u
#define LISP65_BYTECODE_STDLIB_DIRECTORY_BYTES 2786u
#define LISP65_BYTECODE_STDLIB_LITERAL_INDEX_COUNT 970u
#define LISP65_BYTECODE_STDLIB_LITERAL_NODE_COUNT 970u
#define LISP65_BYTECODE_STDLIB_LITERAL_PATCH_COUNT 878u
#define LISP65_BYTECODE_STDLIB_REPL_BANNER_ENTRY 239u
#define LISP65_BYTECODE_STDLIB_NATIVE_READ_LINE_ENTRY 395u

#if defined(LISP65_STDLIB_BOOT_OVERLAY)
#define LISP65_STDLIB_BOOTDATA __attribute__((section(".lisp65_boot"), used))
#else
#define LISP65_STDLIB_BOOTDATA
#endif

typedef struct {
    uint8_t kind;
    int16_t value;
    uint16_t first;
    uint16_t count;
    const char *name;
} lisp65_bc_literal_node;

typedef struct {
    const char *name;
    uint32_t ext_addr;
    uint8_t flags;
    uint16_t blob_offset;
    uint16_t length;
    uint16_t lit_first;
    uint8_t lit_count;
} lisp65_bc_stdlib_entry;

typedef struct {
    uint16_t blob_offset;
    uint16_t node;
} lisp65_bc_literal_patch;

/* Defined in the generated .c unless LISP65_STDLIB_EXTERNAL_BLOB is set.
 * Literal-table obj words in the blob are host placeholders; native loaders must
 * rewrite them before running. */
#ifndef LISP65_STDLIB_EXTERNAL_BLOB
extern const uint8_t lisp65_stdlib_blob[];
#endif /* LISP65_STDLIB_EXTERNAL_BLOB */
#define lisp65_bytecode_stdlib_blob lisp65_stdlib_blob

/* Defined by compiling the generated .c with LISP65_BYTECODE_STDLIB_EMIT_METADATA.
 * The native MVP VM stdlib target enables this flag so the C materializer can patch
 * literal-table obj words before running embedded bytecode. */
extern const uint16_t lisp65_bytecode_stdlib_literal_index[];
extern const lisp65_bc_literal_node lisp65_bytecode_stdlib_literal_nodes[];
extern const lisp65_bc_literal_patch lisp65_bytecode_stdlib_literal_patches[];

/* Optional full review metadata; not needed by the native boot materializer. */
#ifdef LISP65_BYTECODE_STDLIB_EMIT_FULL_METADATA
extern const uint8_t lisp65_bytecode_stdlib_directory[];
extern const lisp65_bc_stdlib_entry lisp65_bytecode_stdlib_entries[];
#endif /* LISP65_BYTECODE_STDLIB_EMIT_FULL_METADATA */

/* K3 boot-loader view: use an external/preloaded blob or stage lisp65_stdlib_blob,
 * materialize/patch literals, then register lisp65_embed. */
#ifdef LISP65_VM
#include "vm_registry.h"
extern const uint16_t lisp65_stdlib_blob_len;
extern const uint8_t lisp65_stdlib_bank;
extern const uint16_t lisp65_stdlib_off;
extern const vm_embed_entry lisp65_embed[];
extern const uint16_t lisp65_embed_count;
#define lisp65_bytecode_stdlib_embed lisp65_embed
#endif /* LISP65_VM */

/* suite: build/c2.3/v1.9.0-release-card-r1-preflight/native-client-product-stdlib-suite.json */
/* format: lisp65-bytecode-p0-stdlib-subset-v1 */

#endif /* LISP65_BYTECODE_STDLIB_P0_H */
