; Generated from v1.3 shelf directory-only entry refs; do not edit.
(defun %comfort-callers-index ()
  '(
    (%ide-apply-page-command %ide-apply-rare-edit-command)
    (%ide-apply-rare-edit-command %ide-x)
    (%ide-apply-region-command %ide-apply-rare-edit-command)
    (%ide-apply-word-edit-command %ide-apply-rare-edit-command)
    (%ide-buffer-with-mark %ide-kill-region-lines ide-exchange-point-and-mark ide-kill-region ide-set-mark)
    (%ide-execute-command-submit %ide-x)
    (%ide-kill-region-lines ide-kill-region)
    (%ide-mini-search-submit %ide-x)
    (%ide-page-rows %ide-apply-page-command)
    (%ide-region-bounds ide-kill-region ide-region-text)
    (%ide-region-parts %ide-kill-region-lines ide-region-text)
    (%ide-region-parts-tail %ide-region-parts %ide-region-parts-tail)
    (%ide-search-lines %ide-search-lines %ide-search-lines-from)
    (%ide-search-lines-from %ide-mini-search-submit %ide-search-lines-from)
    (%ide-word-scan %ide-word-scan ide-move-word-left ide-move-word-right)
    (%m65d-bam-change %m65d-bam-change %m65d-claim-new %m65d-release-half)
    (%m65d-bam-find %m65d-bam-find %m65d-write-plan)
    (%m65d-bam-header-ok-p %m65d-check-old-half %m65d-claim-new %m65d-release-half %m65d-write-plan m65d-remount)
    (%m65d-bam-validate-tracks %m65d-bam-validate-tracks m65d-remount)
    (%m65d-before-write %m65d-claim-new %m65d-commit-dir %m65d-release-half %m65d-write-chain)
    (%m65d-bit-free-p %m65d-bam-find %m65d-chain-state %m65d-count-free)
    (%m65d-bitmap-off %m65d-bam-change %m65d-bit-free-p)
    (%m65d-blocks-for %m65d-blocks-for %m65d-run-record)
    (%m65d-chain-state %m65d-chain-state %m65d-check-old-half %m65d-claim-new %m65d-release-half)
    (%m65d-check-old-half %m65d-old-validated)
    (%m65d-claim-new %m65d-write-plan)
    (%m65d-clear %m65d-write-chain)
    (%m65d-commit-dir %m65d-write-plan)
    (%m65d-copy %m65d-write-chain)
    (%m65d-count-free %m65d-bam-find %m65d-bam-validate-tracks %m65d-chain-state %m65d-count-free)
    (%m65d-dir-entries %m65d-dir-entries %m65d-dir-scan)
    (%m65d-dir-fill %m65d-commit-dir)
    (%m65d-dir-scan %m65d-dir-scan %m65d-run-source m65d-remount)
    (%m65d-dir-write-name %m65d-dir-fill %m65d-dir-write-name)
    (%m65d-entry-valid-p %m65d-dir-entries)
    (%m65d-mask %m65d-bam-change %m65d-bit-free-p)
    (%m65d-media-detail %m65d-media-detail %m65d-media-kind %m65d-run)
    (%m65d-media-kind %m65d-before-write %m65d-run m65d-remount)
    (%m65d-name-chars-ok-p %m65d-name-chars-ok-p %m65d-run-authorized)
    (%m65d-old-validated %m65d-run-record)
    (%m65d-pair-member-p %m65d-pair-member-p %m65d-read-old-chain)
    (%m65d-read-old-chain %m65d-read-old-chain %m65d-run-record)
    (%m65d-release-half %m65d-write-plan)
    (%m65d-run m65d-save m65d-save-new)
    (%m65d-run-authorized %m65d-run)
    (%m65d-run-record %m65d-run-source)
    (%m65d-run-source %m65d-run-authorized)
    (%m65d-set %m65d-bam-find %m65d-before-write %m65d-claim-new %m65d-commit-dir %m65d-dir-entries %m65d-dir-scan %m65d-old-validated %m65d-read-old-chain %m65d-run %m65d-run-authorized %m65d-run-record %m65d-run-source %m65d-write-plan m65d-remount m65d-save-new)
    (%m65d-write-chain %m65d-write-chain %m65d-write-plan)
    (%m65d-write-plan %m65d-run-record)
    ))

(defun who-calls (name)
  ((lambda (row) (if row (cdr row) nil))
   (assoc name (%comfort-callers-index))))
