; Generated by tools/host-lisp/comfort_state_address.py.
; Do not edit: config/comfort-default-native/linker/full-map-linker/c.ld is the address authority.

(defun %comfort-state-hi () 191)
(defun %comfort-state-lo () 246)
