;; Generated by tools/host-lisp/v11_l_lite_keymap.py from
;; config/v11-l-lite-keymap.json. Do not edit this file directly.

(defun ide-printable-code-p (code)
  (and (>= code 32) (<= code 126)))

(defun %ide-keymap-lookup (code table)
  (if table
      (if (= code (car table))
          (car (cdr table))
          (%ide-keymap-lookup code (cdr (cdr table))))
      nil))

(defun %ide-prefix-command (code)
  (progn
    (set-symbol-value (quote ide-event-command) nil)
    (%ide-keymap-lookup code (quote (19 1001 6 1002 23 1004 2 1006 4 1007 11 1008 14 1009 16 1010 1 1120 5 1121 18 1122 24 1123 25 1124 32 1115 3 1015 120 1013 13 1013)))))

(defun %ide-base-command (code)
  (%ide-keymap-lookup code (quote (13 1109 20 1101 157 1106 29 1107 145 1108 17 1003 4 1102 6 1107 2 1106 19 1011 12 1012 14 1003 16 1108 10 1109 1 1104 5 1103 15 1111 21 1112 23 1113 18 1114 22 1116 26 1117 11 1118 25 1119))))

(defun %ide-command-route (command)
  (%ide-keymap-lookup command (quote (1001 4 1002 5 1003 1 1004 6 1006 7 1007 8 1008 9 1009 10 1010 11 1011 12 1012 12 1013 12 1014 12 1015 13 1101 1 1102 1 1103 3 1104 2 1106 1 1107 1 1108 1 1109 1 1110 1 1111 1 1112 1 1113 1 1114 1 1115 1 1116 1 1117 1 1118 1 1119 1 1120 1 1121 1 1122 1 1123 1 1124 1))))

(defun %ide-direct-p (command)
  (eq (%ide-command-route command) 1))

(defun ide-event-command (event)
  ((lambda (code)
     (if (eq (symbol-value (quote ide-event-command)) 24)
         (%ide-prefix-command code)
         (if (= code 24)
             (progn (set-symbol-value (quote ide-event-command) 24) nil)
             ((lambda (command)
                (if command
                    command
                    (if (and (>= code 32)
                             (<= code 126))
                        1110
                        nil)))
              (%ide-base-command code)))))
   (ide-event-code event)))

(defun ide-command-names ()
  (list "find-file" "save-buffer" "compile-load" "goto-line" "eval-buffer"))

(defun %ide-command-named (name)
  (cond
        ((string= name "find-file") 1002)
        ((string= name "save-buffer") 1001)
        ((string= name "compile-load") 1008)
        ((string= name "goto-line") 1012)
        ((string= name "eval-buffer") 1014)
        (t nil)))
