/* Derived from selected delivery population. */
#define LISP65_DELIVERY_R3_DESCRIPTOR_BYTES 336u
#define LISP65_DELIVERY_R3_DESCRIPTOR_RECORDS 10u
#define LISP65_DELIVERY_R3_ROLE_LAST 10u
#define LISP65_DELIVERY_R3_ROLE_MASK 1023u
