# Internal dialect-v2 Runtime-Core proof. This profile is never a Ship input.

V2_RUNTIME_CORE_PROOF_CONTRACT := config/v2-runtime-core-proof.json
V2_RUNTIME_CORE_PROOF_DIR := build/products/runtime-core-v2-proof
V2_RUNTIME_CORE_PROOF_LINK_A := $(V2_RUNTIME_CORE_PROOF_DIR)/link-a/runtime.prg
V2_RUNTIME_CORE_PROOF_LINK_B := $(V2_RUNTIME_CORE_PROOF_DIR)/link-b/runtime.prg
V2_RUNTIME_CORE_PROOF_PROFILE := $(V2_RUNTIME_CORE_PROOF_DIR)/resolved-profile.txt
V2_RUNTIME_CORE_PROOF_PRELOAD := $(V2_RUNTIME_CORE_PROOF_DIR)/runtime-preload.bin
V2_RUNTIME_CORE_PROOF_PRELOAD_HEADER := $(V2_RUNTIME_CORE_PROOF_DIR)/runtime-preload-contract.h
V2_RUNTIME_CORE_PROOF_FOOTPRINT := $(V2_RUNTIME_CORE_PROOF_DIR)/footprint.txt
V2_RUNTIME_CORE_PROOF_AUDIT := $(V2_RUNTIME_CORE_PROOF_DIR)/audit.txt
V2_RUNTIME_CORE_PROOF_ELF_AUDIT := $(V2_RUNTIME_CORE_PROOF_DIR)/elf-audit.json
V2_RUNTIME_CORE_PROOF_REPRO := $(V2_RUNTIME_CORE_PROOF_DIR)/reproducibility.json
V2_RUNTIME_CORE_PROOF_HOST := $(V2_RUNTIME_CORE_PROOF_DIR)/runtime-core-host
V2_RUNTIME_CORE_PROOF_HOST_REPORT := $(V2_RUNTIME_CORE_PROOF_DIR)/host-smoke.txt
V2_RUNTIME_CORE_PROOF_TOOLCHAIN := $(V2_RUNTIME_CORE_PROOF_DIR)/toolchain.txt
V2_RUNTIME_CORE_PROOF_CANDIDATE := $(V2_RUNTIME_CORE_PROOF_DIR)/candidate

V2_RUNTIME_CORE_PROOF_ARTIFACT_PREFIX := build/bytecode/dialect-v2/runtime-core/stdlib-p0
V2_RUNTIME_CORE_PROOF_ARTIFACT_C := $(V2_RUNTIME_CORE_PROOF_ARTIFACT_PREFIX).c
V2_RUNTIME_CORE_PROOF_ARTIFACT_HEADER := $(V2_RUNTIME_CORE_PROOF_ARTIFACT_PREFIX).h
V2_RUNTIME_CORE_PROOF_ARTIFACT_EXT := $(V2_RUNTIME_CORE_PROOF_ARTIFACT_PREFIX).ext.bin
V2_RUNTIME_CORE_PROOF_ARTIFACT_MANIFEST := $(V2_RUNTIME_CORE_PROOF_ARTIFACT_PREFIX).manifest.json
V2_RUNTIME_CORE_PROOF_INVENTORY := build/bytecode/dialect-v2/runtime-core/service-inventory.json

V2_RUNTIME_CORE_PROOF_CFLAGS := $(RUNTIME_CORE_CFLAGS) -ffile-prefix-map=$(CURDIR)=.
V2_RUNTIME_CORE_PROOF_V2_DEFINES := \
	-DLISP65_DIALECT_V2 \
	-DLISP65_V2_NATIVE_CAPABILITIES \
	-DLISP65_V2_NATIVE_STRING_CODECS \
	-DLISP65_TREEWALK_STRIP \
	-DLISP65_V2_SERVICE_REGISTRY_CLOSED \
	-DLISP65_V2_CARRIER_CUT
V2_RUNTIME_CORE_PROOF_DEFINES := $(RUNTIME_CORE_DEFINES) \
	$(V2_RUNTIME_CORE_PROOF_V2_DEFINES)
V2_RUNTIME_CORE_PROOF_HOST_DEFINES := \
	-DLISP65_RUNTIME_CORE -DVM_CODEBUF=56 \
	-DGC_ROOTS=128 -DLISP65_MARK_BITMAP \
	-DLISP65_EXT_HEAP -DEXT_CELLS=1024 \
	-DLISP65_STRING_ARENA -DSTR_ARENA_SIZE=0x2480 \
	-DLISP65_VM_GLOBAL_PRIMS -DLISP65_VM_NATIVE_APPLY \
	-DNAMEPOOL=9536 -DMAX_SYM=720 -DVM_DIR_MAX=552 \
	$(V2_RUNTIME_CORE_PROOF_V2_DEFINES)
