# Explicit evaluator-free Runtime Core prototype. Do not inherit Workbench flags.

RUNTIME_CORE_PROFILE_ID := runtime-core-prototype-v1
RUNTIME_CORE_ENTRY := runtime-main
RUNTIME_CORE_DIR := build/products/runtime-core
RUNTIME_CORE_BYTECODE_DIR := $(RUNTIME_CORE_DIR)/bytecode
RUNTIME_CORE_STDLIB_PREFIX := $(RUNTIME_CORE_BYTECODE_DIR)/stdlib-p0
RUNTIME_CORE_STDLIB_HEADER := $(RUNTIME_CORE_STDLIB_PREFIX).h
RUNTIME_CORE_STDLIB_C := $(RUNTIME_CORE_STDLIB_PREFIX).c
RUNTIME_CORE_STDLIB_BLOB := $(RUNTIME_CORE_STDLIB_PREFIX).ext.bin
RUNTIME_CORE_STDLIB_MANIFEST := $(RUNTIME_CORE_STDLIB_PREFIX).manifest.json
RUNTIME_CORE_SUITE := tests/bytecode/runtime/p0-runtime-export-app-v1.json
RUNTIME_EXPORT_CONTRACT := config/runtime-export-contract.json
RUNTIME_EXPORT_APP := tests/bytecode/runtime/runtime-app-v1.json
RUNTIME_EXPORT_APP_PREFIX := $(RUNTIME_CORE_DIR)/runtime-app
RUNTIME_EXPORT_HOST_APP_IMAGE := $(RUNTIME_EXPORT_APP_PREFIX).ext.bin
RUNTIME_EXPORT_APP_MANIFEST := $(RUNTIME_EXPORT_APP_PREFIX).manifest.json
RUNTIME_EXPORT_WORKBENCH_GOLDEN_DIR := tests/bytecode/runtime/workbench-golden-v1
RUNTIME_EXPORT_APP_IMAGE := $(RUNTIME_EXPORT_WORKBENCH_GOLDEN_DIR)/runtime-app.l65m
RUNTIME_EXPORT_WORKBENCH_REEMITTED_IMAGE := $(RUNTIME_EXPORT_WORKBENCH_GOLDEN_DIR)/reemitted-runtime-app.l65m
RUNTIME_EXPORT_WORKBENCH_EMISSION_RECEIPT := $(RUNTIME_EXPORT_WORKBENCH_GOLDEN_DIR)/emission-receipt.json
RUNTIME_EXPORT_WORKBENCH_REEMISSION_RECEIPT := $(RUNTIME_EXPORT_WORKBENCH_GOLDEN_DIR)/reemission-receipt.json
RUNTIME_EXPORT_WORKBENCH_SHIP_MANIFEST := tests/bytecode/runtime/evidence/ap8.1-g5-78083d6/ship-manifest.json
RUNTIME_EXPORT_DIR := build/products/runtime-export
RUNTIME_EXPORT_STAGING_DIR := $(RUNTIME_EXPORT_DIR)/staging
RUNTIME_EXPORT_CANDIDATE_DIR := $(RUNTIME_EXPORT_DIR)/candidate
RUNTIME_EXPORT_REPRO_BASELINE_DIR := $(RUNTIME_EXPORT_DIR)/reproducibility-baseline
RUNTIME_EXPORT_RESOLVED_PROFILE := $(RUNTIME_EXPORT_STAGING_DIR)/resolved-profile.txt
RUNTIME_EXPORT_TOOLCHAIN_REPORT := $(RUNTIME_EXPORT_STAGING_DIR)/toolchain-report.txt
RUNTIME_EXPORT_BOUND_PRELOAD := $(RUNTIME_EXPORT_STAGING_DIR)/runtime-preload.bin
RUNTIME_EXPORT_WORKBENCH_PRELOAD := $(RUNTIME_EXPORT_STAGING_DIR)/workbench-runtime-preload.bin
RUNTIME_EXPORT_PRELOAD_HEADER := $(RUNTIME_EXPORT_STAGING_DIR)/runtime-preload-contract.h
RUNTIME_EXPORT_WORKBENCH_GOLDEN_REPORT := $(RUNTIME_EXPORT_STAGING_DIR)/workbench-golden-report.json
RUNTIME_EXPORT_HW_ORACLE := $(RUNTIME_EXPORT_DIR)/hardware-oracle.json
RUNTIME_EXPORT_G4_PLAN := $(RUNTIME_EXPORT_DIR)/g4-plan.txt
RUNTIME_EXPORT_G4_PHASE_DIR := $(RUNTIME_EXPORT_DIR)/g4-phases
RUNTIME_EXPORT_MISMATCH_DIR := $(RUNTIME_EXPORT_DIR)/build-id-mismatch
RUNTIME_EXPORT_G5_EVIDENCE_DIR ?= build/hw/runtime-export-g5
RUNTIME_EXPORT_G5_POWER_CYCLE_TOKEN ?=
RUNTIME_EXPORT_G5_CYCLE_ID ?=
RUNTIME_EXPORT_G5_DEVICE ?= /dev/ttyUSB1
RUNTIME_EXPORT_G5_TOOLS ?= tools/m65tools
RUNTIME_CORE_PRG := $(RUNTIME_CORE_DIR)/lisp65-runtime-core.prg
RUNTIME_CORE_FOOTPRINT_REPORT := $(RUNTIME_CORE_DIR)/footprint.txt

# Non-default AP4.3 boot-overlay prototype.  These artifacts are deliberately
# profile-bound and must never be paired with another Runtime Core build.
RUNTIME_CORE_OVERLAY_DIR := $(RUNTIME_CORE_DIR)/overlay-prototype
RUNTIME_CORE_OVERLAY_LINKED_PRG := $(RUNTIME_CORE_OVERLAY_DIR)/lisp65-runtime-core-overlay-linked.prg
RUNTIME_CORE_OVERLAY_RESIDENT_PRG := $(RUNTIME_CORE_OVERLAY_DIR)/lisp65-runtime-core-resident.prg
RUNTIME_CORE_OVERLAY_RAW := $(RUNTIME_CORE_OVERLAY_DIR)/lisp65-runtime-core-overlay.bin
RUNTIME_CORE_OVERLAY_PACKAGE_DIR := $(RUNTIME_CORE_OVERLAY_DIR)/package
RUNTIME_CORE_OVERLAY_PACKAGE_RAW := $(RUNTIME_CORE_OVERLAY_PACKAGE_DIR)/overlay.bin
RUNTIME_CORE_OVERLAY_MANIFEST := $(RUNTIME_CORE_OVERLAY_PACKAGE_DIR)/manifest.json
RUNTIME_CORE_OVERLAY_ABI_CONTRACT := $(RUNTIME_CORE_OVERLAY_DIR)/resolved-profile.txt
RUNTIME_CORE_OVERLAY_ABI_ID := runtime-core-overlay-abi-v1
RUNTIME_CORE_OVERLAY_LD := scripts/lisp65-mega65-runtime-core-overlay.ld
RUNTIME_CORE_OVERLAY_SECTION := .lisp65_runtime_core_overlay
RUNTIME_CORE_OVERLAY_VMA := 0xb800
RUNTIME_CORE_OBJCOPY := $(LLVM)/llvm-objcopy

# Reset-safe AP4.3 Runtime Core path: the boot overlay stays in one flat PRG
# immediately behind .noinit.  This is independent of the fixed-$b800 split
# package above, which remains a diagnostic prototype.
RUNTIME_CORE_INLINE_OVERLAY_DIR := $(RUNTIME_CORE_DIR)/inline-overlay-prototype
RUNTIME_CORE_INLINE_OVERLAY_PRG := $(RUNTIME_CORE_INLINE_OVERLAY_DIR)/lisp65-runtime-core-inline-overlay.prg
RUNTIME_CORE_INLINE_OVERLAY_FOOTPRINT_REPORT := $(RUNTIME_CORE_INLINE_OVERLAY_DIR)/footprint.txt
RUNTIME_CORE_INLINE_OVERLAY_AUDIT_REPORT := $(RUNTIME_CORE_INLINE_OVERLAY_DIR)/audit.txt
RUNTIME_CORE_INLINE_OVERLAY_LD := scripts/lisp65-mega65-runtime-core-inline-overlay.ld
RUNTIME_CORE_INLINE_OVERLAY_MIN_BOOT_STACK_GAP = $(RUNTIME_CORE_MIN_BOOT_STACK_GAP)
RUNTIME_CORE_INLINE_OVERLAY_RUNTIME_STACK_BUDGET = $(RUNTIME_CORE_MIN_STACK_GAP)
RUNTIME_CORE_INLINE_OVERLAY_MIN_POST_BOOT_RESERVE = $(RUNTIME_CORE_MIN_BANK0_RESERVE)
RUNTIME_CORE_INLINE_OVERLAY_MAX_FILE_END = $(RUNTIME_CORE_MAX_PRG_FILE_END)

RUNTIME_CORE_CFLAGS := -Oz -Wall
RUNTIME_CORE_LDFLAGS := -Wl,--icf=all
RUNTIME_CORE_HEAP_CELLS := 48
RUNTIME_CORE_DEFINES := \
	-DLISP65_RUNTIME_CORE \
	-DVM_CODEBUF=56 \
	-DLISP65_SYMPOOL_EXT \
	-DLISP65_SYMVAL_EXT \
	-DLISP65_NAMEOFF_EXT \
	-DLISP65_SYMFN_EXT \
	-DGC_ROOTS=128 \
	-DLISP65_STDLIB_EXT_METADATA \
	-DLISP65_STDLIB_EXTERNAL_BLOB \
	-DLISP65_MARK_BITMAP \
	-DLISP65_EXT_HEAP \
	-DEXT_CELLS=1024 \
	-DLISP65_NURSERY_HYSTERESIS=192 \
	-DLISP65_STRING_ARENA \
	-DSTR_ARENA_SIZE=0x2480 \
	-DDISK_EXT_BASE=0x6900 \
	-DDISK_EXT_FILE_MAX=0x9600 \
	-DLISP65_VM_GLOBAL_PRIMS \
	-DLISP65_VM_NATIVE_APPLY \
	-DSYMPOOL_EXT_OFF=0xc9e0 \
	-DNAMEPOOL=9536 \
	-DMAX_SYM=720 \
	-DVM_DIR_MAX=552
RUNTIME_CORE_PRELOAD_DEFINE := -include $(RUNTIME_EXPORT_PRELOAD_HEADER)

RUNTIME_CORE_MIN_STACK_GAP := 8192
RUNTIME_CORE_MIN_BOOT_STACK_GAP := 512
RUNTIME_CORE_MIN_BANK0_RESERVE := 8192
RUNTIME_CORE_BANK0_RESERVE_TARGET := 12288
RUNTIME_CORE_MAX_PRG_FILE_END := 0xb000
RUNTIME_CORE_MIN_SYMBOL_HEADROOM := 64
