; lcc execution corpus (self-hosting P2/P3): the same forms through the C compiler (vm) and
; lcc (Lisp-Compiler -> bc_assemble -> vm_run) — Ergebnis-Diff = End-to-End-Semantik-Beweis.
; Surface = lcc P3 including closures, without &rest. Defuns register for later forms.
(+ 1 2)
(if (< 1 2) 10 20)
(cond ((> 1 2) 10) ((> 2 1) 20) (t 30))
(and 1 2 3)
(or nil nil 7)
(when (< 1 2) 99)
(unless (< 1 2) 99)
(let ((x 3) (y 4)) (+ x y))
(let* ((x 3) (y (+ x 1))) (* x y))
(let ((x 1)) (progn (setq x (+ x 41)) x))
(defun sq (x) (* x x))
(sq 7)
(defun fact (n) (if (< n 2) 1 (* n (fact (- n 1)))))
(fact 6)
(defun loopy (n acc) (if (< n 1) acc (loopy (- n 1) (+ acc n))))
(loopy 100 0)
(defun add3 (a b c) (+ (+ a b) c))
(add3 (sq 2) (fact 3) 1)
(defun pick (x) (cond ((eq x (quote a)) 1) ((eq x (quote b)) 2) (t 99)))
(pick (quote b))
(pick (quote z))
(setq g 41)
(+ g 1)
(setq g (+ g 9))
g
(string-length "abcde")
(car (quote (7 8 9)))
(cons 1 (quote (2 3)))
(defun evenish (n) (if (< n 1) t (oddish (- n 1))))
(defun oddish (n) (if (< n 1) nil (evenish (- n 1))))
(evenish 10)
(oddish 7)
(defun adder (n) (lambda (x) (+ x n)))
(funcall (adder 10) 5)
(defun make-counter () (let ((c 0)) (lambda () (progn (setq c (+ c 1)) c))))
(progn (setq z (make-counter)) 0)
(funcall z)
(funcall z)
(defun outer3 (a) (lambda (b) (lambda (c) (+ a (+ b c)))))
(funcall (funcall (funcall (outer3 1) 2) 3))
(defun mk2 () (lambda (x) (* x 2)))
(funcall (mk2) 21)
((lambda (x y) (* x y)) 6 7)
(defun map1 (f l) (if l (cons (funcall f (car l)) (map1 f (cdr l))) nil))
(map1 (adder 100) (quote (1 2 3)))
