; lcc P0 byte-oracle corpus: each line is one form. scripts/lcc-oracle.py compiles it
; (a) with lcc through the Lisp tree engine and (b) with the host Python compiler
; as (lambda () FORM), comparing exact payload bytes and the literal table
; (length and decoded fixnums). P0 covers literals, quote, binary arithmetic and
; comparisons, list operations, progn, and if.
0
1
127
-1
-128
128
-129
16383
t
nil
(quote x)
(quote (1 2 3))
(quote ((a) b))
(+ 1 2)
(- 10 4)
(* 6 7)
(/ 20 4)
(mod 17 5)
(remainder 17 5)
(< 1 2)
(> 1 2)
(= 5 5)
(eq (quote a) (quote a))
(eql 4 4)
(cons 1 2)
(car (quote (5 6)))
(cdr (quote (5 6)))
(consp (quote (1)))
(not nil)
(null nil)
(progn 1)
(progn 1 2)
(progn 1 2 3)
(if t 1 2)
(if nil 1 2)
(if (< 1 2) 10 20)
(if (< 1 2) 10)
(if t (if nil 1 2) 3)
(+ (if t 1 2) 10)
(if (progn 1 t) 5 6)
(+ (+ 1 2) (* 3 4))
(cons (car (quote (1))) (cdr (quote (2 3))))
(+ 200 300)
(if (eq (quote a) (quote b)) (quote ja) (quote nein))
(cons (quote a) (quote a))
(+ 200 (+ 200 200))
(cons (quote (1)) (quote (1)))
(let ((x 1)) x)
(let ((x 1) (y 2)) (+ x y))
(let* ((x 1) (y (+ x 1))) y)
(let ((x 1)) (progn (setq x 5) x))
(let ((x 1)) (let ((y 2)) (+ x y)))
(progn (let ((x 1)) x) (let ((y 2)) y))
(let ((x 1)) (if x (let ((y 2)) y) 3))
(let ((a 1) (b 2) (c 3) (d 4)) (+ (+ a b) (+ c d)))
(foo 1 2)
(bar)
(foo (bar 1) 2)
(string-length "ab")
(funcall (function foo) 3)
(apply (function foo) (quote (1 2)))
(numberp 5)
(lambda (a b) (+ a b))
(lambda (a) (let ((x 2)) (+ a x)))
(lambda (a b c d) d)
(lambda (a) (progn (setq a 5) a))
(lambda (a b c) (if (< a b) c (+ a b)))
(lambda () (let ((s 0)) (progn (setq s (+ s 1)) s)))
(defun sq (x) (* x x))
(defun fact (n) (if (< n 2) 1 (* n (fact (- n 1)))))
(defun loopy (n acc) (if (< n 1) acc (loopy (- n 1) (+ acc n))))
(defun f (x) (g (h x)))
(defun f2 (x) (progn (g x) (h x)))
(defun f3 (x) (string-length x))
(defun f4 (x) (funcall (function g) x))
(defun f5 (x) (let ((y 1)) (g y)))
(defun f6 (x) (if x (g 1) (progn 2 (h 3))))
(defun f7 (x) (if x (g 1)))
(defun f8 (a b) (let* ((c (+ a 1)) (d (+ b c))) (if (< c d) (f8 c d) c)))
(and 1 2 3)
(and)
(and 1 nil 3)
(or nil 5)
(or)
(or 1 2)
(when 1 2 3)
(when nil 9)
(unless 1 2)
(cond (1 2) (3 4))
(cond (5))
(cond ((> 1 2) 10) ((> 2 1) 20) (t 30))
(defun f (x) (and x (g x)))
(defun f (x) (cond (x (g 1)) (t (h 2))))
(defun f (x) (or (g x) (h x)))
(defun f (x) (when x (g x)))
(defun mk (y) (lambda (x) (* x 2)))
(defun mk2 () (lambda () 7))
