#!/usr/bin/env python3
"""Generate a C header that embeds Lisp source as a C string."""

from __future__ import annotations

from pathlib import Path
import sys


def c_escape(data: bytes) -> str:
    out: list[str] = []
    for byte in data:
        if byte == 0x0A:
            out.append(r"\n")
        elif byte == 0x09:
            out.append(r"\t")
        elif byte == 0x22:
            out.append(r"\"")
        elif byte == 0x5C:
            out.append(r"\\")
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append(f"\\{byte:03o}")
    return "".join(out)


def literal_chunks(data: bytes, width: int = 72) -> list[str]:
    return [c_escape(data[i : i + width]) for i in range(0, len(data), width)] or [""]


def header_guard(name: str) -> str:
    return "LISP65_" + "".join(ch if ch.isalnum() else "_" for ch in name.upper()) + "_H"


def main(argv: list[str]) -> int:
    if len(argv) not in (3, 4):
        print(
            "usage: embed-prelude.py source.lisp output.h [c_variable]",
            file=sys.stderr,
        )
        return 2

    src = Path(argv[1])
    dst = Path(argv[2])
    var = argv[3] if len(argv) == 4 else "prelude_src"
    guard = header_guard(dst.stem)
    data = src.read_bytes()
    lines = [
        "/* Generated by scripts/embed-prelude.py; do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"const char {var}[] =",
    ]
    lines.extend(f'    "{chunk}"' for chunk in literal_chunks(data))
    lines.extend(["    ;", "", f"#endif /* {guard} */", ""])

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
