/* C2 product runtime: the sole immutable/session code-address domain. */
#ifndef LISP65_C2_PRODUCT_RUNTIME_H
#define LISP65_C2_PRODUCT_RUNTIME_H

#include <stdint.h>
#include "obj.h"

#define LISP65_C2_CODE_BANK_TAG 0xfeu
#define LISP65_C2D_BANK 5u
#define LISP65_C2D_BASE 0u
#define LISP65_C2D_BYTES 33840u
#define LISP65_C2D_REGION_BYTES 50816u

/* Resident Bank-5 C2D transport.  Public consumers must impose their own
 * narrower semantic domain before calling the region-level reader. */
uint8_t c2_stream_c2d_read(uint16_t offset, void *dst, uint16_t length);
#define LISP65_C2_SHELF_PHYSICAL 0x08100000UL
#define LISP65_C2_SESSION_PHYSICAL 0x08400000UL
#define LISP65_C2_SESSION_BYTES 0x00100000UL
#ifdef LISP65_C2_NESTED_APPEND_V5
#ifdef LISP65_C2_RUNTIME_LIFETIME_FAMILIES
#define LISP65_C2_APPEND_ROOTS_SLOT 24u
#define LISP65_C2_APPEND_FRONTS_SLOT 25u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_SLOT 26u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_SLOT 27u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 28u
#define LISP65_C2_APPEND_STAGE_SLOT 29u
#define LISP65_C2_APPEND_IMAGE_SLOT 30u
#define LISP65_C2_APPEND_ENTRIES_SLOT 31u
#define LISP65_C2_APPEND_HEADER_SLOT 32u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 33u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 34u
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 35u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 36u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 37u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 38u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 39u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 40u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 41u
#endif
#else
#define LISP65_C2_APPEND_ROOTS_SLOT 30u
#define LISP65_C2_APPEND_FRONTS_SLOT 31u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_SLOT 32u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_SLOT 33u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 34u
#define LISP65_C2_APPEND_STAGE_SLOT 35u
#define LISP65_C2_APPEND_IMAGE_SLOT 36u
#define LISP65_C2_APPEND_ENTRIES_SLOT 37u
#define LISP65_C2_APPEND_HEADER_SLOT 38u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 39u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 40u
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 41u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 42u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 43u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 44u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 45u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 46u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 47u
#endif
#endif
#endif
#ifdef LISP65_C2_RUNTIME_LIFETIME_FAMILIES
/* Boot phases and session phases deliberately reuse dense L65R slot IDs.
 * The runtime family check is therefore part of every C2 transport call. */
#define LISP65_C2_PHASE_00_SLOT 2u
#define LISP65_C2_PHASE_00B_SLOT 3u
#define LISP65_C2_PHASE_01_SLOT 4u
#define LISP65_C2_PHASE_02A_SLOT 5u
#define LISP65_C2_PHASE_02B_SLOT 6u
#define LISP65_C2_PHASE_03_SLOT 7u
#ifdef LISP65_C2_LITE_BANK2_STAGING
#define LISP65_C2_PHASE_03B_SLOT 8u
#endif
#define LISP65_C2_PHASE_04_SLOT 2u
#define LISP65_C2_PHASE_05_SLOT 3u
#define LISP65_C2_PHASE_06A_SLOT 4u
#define LISP65_C2_PHASE_06B_SLOT 5u
#define LISP65_C2_PHASE_07_SLOT 6u
#define LISP65_C2_PHASE_08_SLOT 7u
#define LISP65_C2_PHASE_09_SLOT 8u
#define LISP65_C2_PHASE_10_SLOT 9u
#define LISP65_C2_PHASE_11_SLOT 10u
#define LISP65_C2_PHASE_12_SLOT 11u
#define LISP65_C2_PHASE_13_SLOT 12u
#define LISP65_C2_EMIT_PREPARE_SLOT 13u
#define LISP65_C2_EMIT_NAME_SLOT 14u
#define LISP65_C2_EMIT_LITERAL_PREP_SLOT 15u
#define LISP65_C2_EMIT_LITERAL_ATOM_SLOT 16u
#define LISP65_C2_EMIT_LITERAL_APPEND_SLOT 17u
#define LISP65_C2_EMIT_CODE_SLOT 18u
#define LISP65_C2_EMIT_FINAL_META_SLOT 19u
#define LISP65_C2_EMIT_FINAL_CRC_SLOT 20u
#define LISP65_C2_APPEND_ENVELOPE_SLOT 21u
#define LISP65_C2_APPEND_CRC_SLOT 22u
#define LISP65_C2_APPEND_METADATA_SLOT 23u
#ifndef LISP65_C2_NESTED_APPEND_V5
#define LISP65_C2_APPEND_CAPACITY_SLOT 24u
#define LISP65_C2_APPEND_STAGE_SLOT 25u
#define LISP65_C2_APPEND_IMAGE_SLOT 26u
#define LISP65_C2_APPEND_ENTRIES_SLOT 27u
#define LISP65_C2_APPEND_HEADER_SLOT 28u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 29u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 30u
#define LISP65_C2_APPEND_ROLLBACK_SLOT 31u
#endif
#else
#define LISP65_C2_PHASE_00_SLOT 2u
#define LISP65_C2_PHASE_00B_SLOT 3u
#define LISP65_C2_PHASE_01_SLOT 4u
#define LISP65_C2_PHASE_02A_SLOT 5u
#define LISP65_C2_PHASE_02B_SLOT 6u
#define LISP65_C2_PHASE_03_SLOT 7u
#ifdef LISP65_C2_LITE_BANK2_STAGING
#define LISP65_C2_PHASE_03B_SLOT 8u
#endif
#define LISP65_C2_PHASE_04_SLOT 8u
#define LISP65_C2_PHASE_05_SLOT 9u
#define LISP65_C2_PHASE_06A_SLOT 10u
#define LISP65_C2_PHASE_06B_SLOT 11u
#define LISP65_C2_PHASE_07_SLOT 12u
#define LISP65_C2_PHASE_08_SLOT 13u
#define LISP65_C2_PHASE_09_SLOT 14u
#define LISP65_C2_PHASE_10_SLOT 15u
#define LISP65_C2_PHASE_11_SLOT 16u
#define LISP65_C2_PHASE_12_SLOT 17u
#define LISP65_C2_PHASE_13_SLOT 18u
#define LISP65_C2_EMIT_PREPARE_SLOT 19u
#define LISP65_C2_EMIT_NAME_SLOT 20u
#define LISP65_C2_EMIT_LITERAL_PREP_SLOT 21u
#define LISP65_C2_EMIT_LITERAL_ATOM_SLOT 22u
#define LISP65_C2_EMIT_LITERAL_APPEND_SLOT 23u
#define LISP65_C2_EMIT_CODE_SLOT 24u
#define LISP65_C2_EMIT_FINAL_META_SLOT 25u
#define LISP65_C2_EMIT_FINAL_CRC_SLOT 26u
#define LISP65_C2_APPEND_ENVELOPE_SLOT 27u
#define LISP65_C2_APPEND_CRC_SLOT 28u
#define LISP65_C2_APPEND_METADATA_SLOT 29u
#ifndef LISP65_C2_NESTED_APPEND_V5
#define LISP65_C2_APPEND_CAPACITY_SLOT 30u
#define LISP65_C2_APPEND_STAGE_SLOT 31u
#define LISP65_C2_APPEND_IMAGE_SLOT 32u
#define LISP65_C2_APPEND_ENTRIES_SLOT 33u
#define LISP65_C2_APPEND_HEADER_SLOT 34u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 35u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 36u
#define LISP65_C2_APPEND_ROLLBACK_SLOT 37u
#endif
#endif

/* C2-lite's product-only semantic phase-11 cut inserts one Session-family
 * slot.  The historical layout remains byte-for-byte authoritative unless the
 * split feature is explicit; the probe overrides every later slot as one
 * indivisible ABI change. */
#if defined(LISP65_C2_PHASE11_SPLIT) && defined(LISP65_C2_RUNTIME_LIFETIME_FAMILIES)
#undef LISP65_C2_PHASE_11_SLOT
#undef LISP65_C2_PHASE_12_SLOT
#undef LISP65_C2_PHASE_13_SLOT
#define LISP65_C2_PHASE_11A_SLOT 10u
#define LISP65_C2_PHASE_11B_SLOT 11u
#define LISP65_C2_PHASE_12_SLOT 12u
#define LISP65_C2_PHASE_13_SLOT 13u
#undef LISP65_C2_EMIT_PREPARE_SLOT
#undef LISP65_C2_EMIT_NAME_SLOT
#undef LISP65_C2_EMIT_LITERAL_PREP_SLOT
#undef LISP65_C2_EMIT_LITERAL_ATOM_SLOT
#undef LISP65_C2_EMIT_LITERAL_APPEND_SLOT
#undef LISP65_C2_EMIT_CODE_SLOT
#undef LISP65_C2_EMIT_FINAL_META_SLOT
#undef LISP65_C2_EMIT_FINAL_CRC_SLOT
#define LISP65_C2_EMIT_PREPARE_SLOT 14u
#define LISP65_C2_EMIT_NAME_SLOT 15u
#define LISP65_C2_EMIT_LITERAL_PREP_SLOT 16u
#define LISP65_C2_EMIT_LITERAL_ATOM_SLOT 17u
#define LISP65_C2_EMIT_LITERAL_APPEND_SLOT 18u
#define LISP65_C2_EMIT_CODE_SLOT 19u
#define LISP65_C2_EMIT_FINAL_META_SLOT 20u
#define LISP65_C2_EMIT_FINAL_CRC_SLOT 21u
#undef LISP65_C2_APPEND_ENVELOPE_SLOT
#undef LISP65_C2_APPEND_CRC_SLOT
#undef LISP65_C2_APPEND_METADATA_SLOT
#define LISP65_C2_APPEND_ENVELOPE_SLOT 22u
#define LISP65_C2_APPEND_CRC_SLOT 23u
#define LISP65_C2_APPEND_METADATA_SLOT 24u
#ifdef LISP65_C2_NESTED_APPEND_V5
#undef LISP65_C2_APPEND_ROOTS_SLOT
#undef LISP65_C2_APPEND_FRONTS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_SLOT
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_NAMES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_ROOTS_SLOT 25u
#define LISP65_C2_APPEND_FRONTS_SLOT 26u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_SLOT 27u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_SLOT 28u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 29u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 30u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 32u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 33u
#define LISP65_C2_APPEND_STAGE_SLOT 34u
#define LISP65_C2_APPEND_IMAGE_SLOT 35u
#define LISP65_C2_APPEND_ENTRIES_SLOT 36u
#ifdef LISP65_C2_LITE_COLD_EVICTION
#define LISP65_C2_APPEND_PUBLISH_PLAN_SLOT 37u
#define LISP65_C2_APPEND_HEADER_SLOT 38u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 39u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 40u
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 41u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 42u
#else
#define LISP65_C2_APPEND_HEADER_SLOT 37u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 38u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 39u
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 40u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 41u
#endif
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#ifdef LISP65_C2_LITE_COLD_EVICTION
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 43u
#else
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 42u
#endif
#endif
#endif
#endif

/* C2-lite v6 adds one decoder cutpoint and four append cutpoints.  This block
 * is one ABI change: every later Session-family slot moves together, while
 * the Boot family and the fixed overlay VMA remain unchanged. */
#ifdef LISP65_C2_LITE_V6_SEMANTIC_SPLITS
#if !defined(LISP65_C2_RUNTIME_LIFETIME_FAMILIES) \
    || !defined(LISP65_C2_PHASE11_SPLIT) \
    || !defined(LISP65_C2_NESTED_APPEND_V5) \
    || !defined(LISP65_C2_LITE_COLD_EVICTION)
#error "C2-lite v6 semantic splits require the complete cold-eviction ABI"
#endif
#undef LISP65_C2_PHASE_05_SLOT
#undef LISP65_C2_PHASE_06A_SLOT
#undef LISP65_C2_PHASE_06B_SLOT
#undef LISP65_C2_PHASE_07_SLOT
#undef LISP65_C2_PHASE_08_SLOT
#undef LISP65_C2_PHASE_09_SLOT
#undef LISP65_C2_PHASE_10_SLOT
#undef LISP65_C2_PHASE_11A_SLOT
#undef LISP65_C2_PHASE_11B_SLOT
#undef LISP65_C2_PHASE_12_SLOT
#undef LISP65_C2_PHASE_13_SLOT
#define LISP65_C2_PHASE_05A_SLOT 3u
#define LISP65_C2_PHASE_05B_SLOT 4u
#define LISP65_C2_PHASE_06A_SLOT 5u
#define LISP65_C2_PHASE_06B_SLOT 6u
#define LISP65_C2_PHASE_07_SLOT 7u
#define LISP65_C2_PHASE_08_SLOT 8u
#define LISP65_C2_PHASE_09_SLOT 9u
#define LISP65_C2_PHASE_10_SLOT 10u
#define LISP65_C2_PHASE_11A_SLOT 11u
#define LISP65_C2_PHASE_11B_SLOT 12u
#define LISP65_C2_PHASE_12_SLOT 13u
#define LISP65_C2_PHASE_13_SLOT 14u

#undef LISP65_C2_EMIT_PREPARE_SLOT
#undef LISP65_C2_EMIT_NAME_SLOT
#undef LISP65_C2_EMIT_LITERAL_PREP_SLOT
#undef LISP65_C2_EMIT_LITERAL_ATOM_SLOT
#undef LISP65_C2_EMIT_LITERAL_APPEND_SLOT
#undef LISP65_C2_EMIT_CODE_SLOT
#undef LISP65_C2_EMIT_FINAL_META_SLOT
#undef LISP65_C2_EMIT_FINAL_CRC_SLOT
#define LISP65_C2_EMIT_PREPARE_SLOT 15u
#define LISP65_C2_EMIT_NAME_SLOT 16u
#define LISP65_C2_EMIT_LITERAL_PREP_SLOT 17u
#define LISP65_C2_EMIT_LITERAL_ATOM_SLOT 18u
#define LISP65_C2_EMIT_LITERAL_APPEND_SLOT 19u
#define LISP65_C2_EMIT_CODE_SLOT 20u
#define LISP65_C2_EMIT_FINAL_META_SLOT 21u
#define LISP65_C2_EMIT_FINAL_CRC_SLOT 22u

#undef LISP65_C2_APPEND_ENVELOPE_SLOT
#undef LISP65_C2_APPEND_CRC_SLOT
#undef LISP65_C2_APPEND_METADATA_SLOT
#undef LISP65_C2_APPEND_ROOTS_SLOT
#undef LISP65_C2_APPEND_FRONTS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_SLOT
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_NAMES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_ENVELOPE_SLOT 23u
#define LISP65_C2_APPEND_CRC_SLOT 24u
#define LISP65_C2_APPEND_METADATA_SLOT 25u
#define LISP65_C2_APPEND_ROOTS_SLOT 26u
#define LISP65_C2_APPEND_FRONTS_SLOT 27u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_BOUNDS_SLOT 28u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_CODE_SLOT 29u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_BOUNDS_SLOT 30u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_CODE_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 32u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 33u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 34u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 35u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 36u
#define LISP65_C2_APPEND_STAGE_COPY_SLOT 37u
#define LISP65_C2_APPEND_STAGE_PLANE_SLOT 38u
#define LISP65_C2_APPEND_IMAGE_SLOT 39u
#define LISP65_C2_APPEND_ENTRIES_SLOT 40u
#define LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT 41u
#define LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT 42u
#define LISP65_C2_APPEND_HEADER_SLOT 43u
#define LISP65_C2_APPEND_PUBLISH_NAMES_SLOT 44u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT 45u
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 46u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 47u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 48u
#endif
#endif

/* The aggregate diet fuses two adjacent, always-serial phase pairs.  It does
 * not change the overlay VMA, slice cap, pack quantum or any family boundary;
 * it only removes two Session catalog records and renumbers later slots. */
#ifdef LISP65_C2_LITE_V6_CORESIDENT_DIET
#ifndef LISP65_C2_LITE_V6_SEMANTIC_SPLITS
#error "C2-lite v6 co-residence requires the semantic-split ABI"
#endif

#undef LISP65_C2_APPEND_CRC_SLOT
#undef LISP65_C2_APPEND_METADATA_SLOT
#undef LISP65_C2_APPEND_ROOTS_SLOT
#undef LISP65_C2_APPEND_FRONTS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_BOUNDS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_CODE_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_BOUNDS_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_CODE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_COPY_SLOT
#undef LISP65_C2_APPEND_STAGE_PLANE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_NAMES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_CRC_METADATA_SLOT 24u
#define LISP65_C2_APPEND_ROOTS_SLOT 25u
#define LISP65_C2_APPEND_FRONTS_SLOT 26u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_BOUNDS_SLOT 27u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_CODE_SLOT 28u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_BOUNDS_SLOT 29u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_CODE_SLOT 30u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 32u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 33u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 34u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 35u
#define LISP65_C2_APPEND_STAGE_COPY_SLOT 36u
#define LISP65_C2_APPEND_STAGE_PLANE_SLOT 37u
#define LISP65_C2_APPEND_IMAGE_SLOT 38u
#define LISP65_C2_APPEND_ENTRIES_SLOT 39u
#define LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT 40u
#define LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT 41u
#define LISP65_C2_APPEND_HEADER_SLOT 42u
#define LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT 43u
/* Range callers use the old semantic end-name; both publication halves now
 * terminate at the sole fused entry. */
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT \
    LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 44u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 45u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 46u
#endif

/* The full-v6 record verifier crosses one pack quantum.  Roots and fronts
 * recover that exact quantum by sharing one transported section while the
 * resident serial driver retains two ordered calls.  Every later Session
 * slot moves as one ABI unit; both semantic names intentionally alias the
 * sole physical record. */
#ifdef LISP65_C2_LITE_V6_ROOTS_FRONTS_CORESIDENT
#ifndef LISP65_C2_LITE_V6_CORESIDENT_DIET
#error "roots/fronts co-residence requires the complete v6 aggregate diet"
#endif
#undef LISP65_C2_APPEND_ROOTS_SLOT
#undef LISP65_C2_APPEND_FRONTS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_BOUNDS_SLOT
#undef LISP65_C2_APPEND_RESERVE_TRANSIENT_CODE_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_BOUNDS_SLOT
#undef LISP65_C2_APPEND_RESERVE_PERSISTENT_CODE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_COPY_SLOT
#undef LISP65_C2_APPEND_STAGE_PLANE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_ROOTS_FRONTS_SLOT 25u
#define LISP65_C2_APPEND_ROOTS_SLOT LISP65_C2_APPEND_ROOTS_FRONTS_SLOT
#define LISP65_C2_APPEND_FRONTS_SLOT LISP65_C2_APPEND_ROOTS_FRONTS_SLOT
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_BOUNDS_SLOT 26u
#define LISP65_C2_APPEND_RESERVE_TRANSIENT_CODE_SLOT 27u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_BOUNDS_SLOT 28u
#define LISP65_C2_APPEND_RESERVE_PERSISTENT_CODE_SLOT 29u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT 30u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 32u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 33u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 34u
#define LISP65_C2_APPEND_STAGE_COPY_SLOT 35u
#define LISP65_C2_APPEND_STAGE_PLANE_SLOT 36u
#define LISP65_C2_APPEND_IMAGE_SLOT 37u
#define LISP65_C2_APPEND_ENTRIES_SLOT 38u
#define LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT 39u
#define LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT 40u
#define LISP65_C2_APPEND_HEADER_SLOT 41u
#define LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT 42u
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT \
    LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 43u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 44u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 45u
#endif
#endif

/* The final aggregate consolidation makes publication and journal clearing
 * two marker-selected entries of one transported record.  Removing the old
 * journal-clear record shifts the intervening physical slots once; both
 * semantic names intentionally alias the sole fused record. */
#ifdef LISP65_C2_LITE_V6_PUBLISH_CLEAR_CORESIDENT
#ifndef LISP65_C2_LITE_V6_ROOTS_FRONTS_CORESIDENT
#error "publish/clear co-residence requires roots/fronts co-residence"
#endif
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_COPY_SLOT
#undef LISP65_C2_APPEND_STAGE_PLANE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT 30u
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 32u
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT 33u
#define LISP65_C2_APPEND_STAGE_COPY_SLOT 34u
#define LISP65_C2_APPEND_STAGE_PLANE_SLOT 35u
#define LISP65_C2_APPEND_IMAGE_SLOT 36u
#define LISP65_C2_APPEND_ENTRIES_SLOT 37u
#define LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT 38u
#define LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT 39u
#define LISP65_C2_APPEND_HEADER_SLOT 40u
#define LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT 41u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 42u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 43u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 44u
#endif

/* Rollback preparation and its immediately following C2J write share one
 * physical Session record.  The existing C2J result byte is the complete
 * NONE/PREPARED/ACTIVE handoff; all later physical slots move together. */
#ifdef LISP65_C2_LITE_V6_JOURNAL_PREPARE_CORESIDENT
#ifndef LISP65_C2_LITE_V6_PUBLISH_CLEAR_CORESIDENT
#error "journal/prepare co-residence requires publish/clear co-residence"
#endif
#undef LISP65_C2_APPEND_JOURNAL_WRITE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT
#undef LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT
#undef LISP65_C2_APPEND_STAGE_COPY_SLOT
#undef LISP65_C2_APPEND_STAGE_PLANE_SLOT
#undef LISP65_C2_APPEND_IMAGE_SLOT
#undef LISP65_C2_APPEND_ENTRIES_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT
#undef LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT
#undef LISP65_C2_APPEND_HEADER_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#undef LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT
#undef LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT
#undef LISP65_C2_APPEND_PUBLISH_CELLS_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_JOURNAL_PREPARE_SLOT 30u
#define LISP65_C2_APPEND_JOURNAL_WRITE_SLOT \
    LISP65_C2_APPEND_JOURNAL_PREPARE_SLOT
#define LISP65_C2_APPEND_ROLLBACK_PREPARE_SLOT \
    LISP65_C2_APPEND_JOURNAL_PREPARE_SLOT
#define LISP65_C2_APPEND_JOURNAL_VALIDATE_SLOT 31u
#define LISP65_C2_APPEND_JOURNAL_RECONSTRUCT_SLOT 32u
#define LISP65_C2_APPEND_STAGE_COPY_SLOT 33u
#define LISP65_C2_APPEND_STAGE_PLANE_SLOT 34u
#define LISP65_C2_APPEND_IMAGE_SLOT 35u
#define LISP65_C2_APPEND_ENTRIES_SLOT 36u
#define LISP65_C2_APPEND_PUBLISH_PLAN_SCAN_SLOT 37u
#define LISP65_C2_APPEND_PUBLISH_PLAN_RESOLVE_SLOT 38u
#define LISP65_C2_APPEND_HEADER_SLOT 39u
#define LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT 40u
#define LISP65_C2_APPEND_JOURNAL_CLEAR_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_PUBLISH_EXPORTS_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_PUBLISH_CELLS_SLOT \
    LISP65_C2_APPEND_PUBLISH_CLEAR_SLOT
#define LISP65_C2_APPEND_ROLLBACK_UNPUBLISH_SLOT 41u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 42u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 43u
#endif
#endif
#endif
#endif

/* Strict L65R-v4 places the rare rollback bodies in the Bank-5 overflow
 * region.  The logical ABI remains one dense Session slot space; region_id
 * qualifies storage, not invocation. */
#ifdef LISP65_C2_TWO_REGION_SESSION_STORE
#if !defined(LISP65_C2_LITE_V6_JOURNAL_PREPARE_CORESIDENT)
#error "two-region Session store requires the complete current append ABI"
#endif
#undef LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT
#undef LISP65_C2_APPEND_ABORT_CONTROL_SLOT
#define LISP65_C2_APPEND_ROLLBACK_WIPE_PLANE_SLOT 42u
#define LISP65_C2_APPEND_ROLLBACK_WIPE_CHIP_SLOT 43u
#define LISP65_C2_APPEND_ROLLBACK_WIPE_ATTIC_SLOT 44u
#define LISP65_C2_APPEND_ROLLBACK_FINALIZE_SLOT 45u
#ifdef LISP65_C2_RESIDENCY_TRIAGE
#define LISP65_C2_APPEND_ABORT_CONTROL_SLOT 46u
#endif
#endif

#if defined(LISP65_C2_LITE_COLD_EVICTION) \
    && (!defined(LISP65_C2_PHASE11_SPLIT) \
        || !defined(LISP65_C2_NESTED_APPEND_V5))
#error "C2-lite cold eviction requires the phase-11 split and C2D-v5 append ABI"
#endif

/* Invalidate all session reachability before enabling the boot-only family. */
uint8_t c2_product_prepare_boot(void);
/* Cold physical-domain transport used by the two C2-lite family stagers.
 * It is the existing C2 DMA seam made explicit; no pointer carries a 28-bit
 * Attic or Chip address. */
void c2_product_physical_copy(uint32_t source, uint32_t target,
                              uint16_t length);

/* Boot validates, resolves and publishes the immutable six-image product. */
uint8_t c2_product_boot(void);

/* Directory and refill seams consumed by vm.c.  `relative` is relative to the
 * normalized code object, never a physical address and never a C pointer. */
uint16_t c2_product_dir_count(void);
uint16_t c2_product_entry_length(uint16_t ordinal);
uint8_t c2_product_entry_read(uint16_t ordinal, uint16_t relative,
                              uint8_t *destination, uint16_t length);

/* Called by the non-moving collector.  The canonical C2D root region is the
 * only value representation; the publication journal is an additional live
 * set only while rollback remains possible. */
void c2_product_gc_mark_roots(void);

/* Central non-local-abort seam.  In the C2D-v5 product this is the sole
 * bridge from every error/RUN-STOP longjmp source to the generation-bound
 * Bank-5 C2J rollback journal.  It is deliberately harmless before the C2
 * session has reached READY. */
uint8_t c2_product_abort_cleanup(void);

/* The sole dynamic-code seam.  It consumes the compiler's detached fnlist,
 * emits one C2I-v2 image, appends it through the shared decoder and either
 * publishes the named main or executes/rolls back an anonymous transient. */
obj c2_product_install(obj fnlist, obj definition_name);

/* Load an already staged one-record C2 image (persistent compile output). */
uint8_t c2_product_append_staged(uint16_t length);

/* Return nonzero only for an exact immutable image in the
 * generation-bound shelf. */
uint8_t c2_product_static_image_named(obj name);

#endif
