/* Stable Lisp error identity. Text is a presentation detail of the active profile. */
#ifndef LISP65_ERROR_CODES_H
#define LISP65_ERROR_CODES_H

#include <stdint.h>
#include "obj.h"

typedef uint8_t lisp65_error_code;

enum {
    LISP65_ERR_NONE = 0,
    LISP65_ERR_STOPPED = 1,
    LISP65_ERR_READER_UNCLOSED_LIST = 2,
    LISP65_ERR_READER_UNCLOSED_STRING = 3,
    LISP65_ERR_READER_UNFINISHED_ESCAPE = 4,
    LISP65_ERR_READER_INVALID_TOKEN = 5,
    LISP65_ERR_READER_TOO_DEEP = 6,
    LISP65_ERR_READER_SYNTAX = 7,
    LISP65_ERR_LCC_INSTALL = 8,
    LISP65_ERR_WRITE_STRING_TYPE = 9,
    LISP65_ERR_COMPILE_STRING_TYPE = 10,
    LISP65_ERR_SAVE_STAGED_TYPE = 11,
    LISP65_ERR_FASL_TYPE = 12,
    LISP65_ERR_EVAL_STRING_TYPE = 13,
    LISP65_ERR_SAVE_ARGS_TYPE = 14,
    LISP65_ERR_SAVE_TOO_LONG = 15,
    LISP65_ERR_DIVISION_BY_ZERO = 16,
    LISP65_ERR_LOAD_TYPE = 17,
    LISP65_ERR_LOAD_OPEN = 18,
    LISP65_ERR_STRING_TO_LIST_TYPE = 19,
    LISP65_ERR_SYMBOL_NAME_TYPE = 20,
    LISP65_ERR_RPLACA_TYPE = 21,
    LISP65_ERR_RPLACD_TYPE = 22,
    LISP65_ERR_SCREEN_WRITE_STRING_TYPE = 23,
    LISP65_ERR_STRING_LENGTH_TYPE = 24,
    LISP65_ERR_STRING_REF_TYPE = 25,
    LISP65_ERR_STRING_REF_RANGE = 26,
    LISP65_ERR_WRITE_CHAR_TYPE = 27,
    LISP65_ERR_UNDEFINED_FUNCTION = 28,
    LISP65_ERR_TOO_MANY_ARGS = 29,
    LISP65_ERR_NOT_A_FUNCTION = 30,
    LISP65_ERR_RECURSION_TOO_DEEP = 31,
    LISP65_ERR_DOTIMES_COUNT_TYPE = 32,
    LISP65_ERR_NO_LCC_RUN = 33,
    LISP65_ERR_TOO_MANY_SYMBOLS = 34,
    LISP65_ERR_STDLIB_BOOT_OVERLAY = 35,
    LISP65_ERR_STDLIB_BOOT_WIPE = 36,
    LISP65_ERR_STDLIB_PROFILED_PRELOAD = 37,
    LISP65_ERR_VM_TYPE = 38,
    LISP65_ERR_VM_STACK = 39,
    LISP65_ERR_VM_OOM = 40,
    LISP65_ERR_VM_UNDEFINED_FUNCTION = 41,
    LISP65_ERR_VM_STEP_LIMIT = 42,
    LISP65_ERR_VM_BAD_BYTECODE = 43,
    LISP65_ERR_STDLIB_METADATA = 44,
    LISP65_ERR_STDLIB_REGISTER = 45,
    LISP65_ERR_RUNTIME_CATALOG = 46,
    LISP65_ERR_RUNTIME_ISLAND = 47,
    LISP65_ERR_WRONG_ARGUMENT_COUNT = 48,
    LISP65_ERR_FASL_ENTRIES_OVERFLOW = 49,
    LISP65_ERR_FASL_NODES_OVERFLOW = 50,
    LISP65_ERR_FASL_NOT_A_DEFUN = 51,
    LISP65_ERR_FASL_OUTPUT_OVERFLOW = 52,
    LISP65_ERR_FASL_PATCHES_OVERFLOW = 53,
    LISP65_ERR_FASL_STRINGS_OVERFLOW = 54,
    LISP65_ERR_FASL_TOO_MANY_HELPERS = 55,
    LISP65_ERR_FASL_UNSUPPORTED_LITERAL = 56,
    LISP65_ERR_FASL_WINDOW_OVERFLOW = 57,
    LISP65_ERR_LCC_DO_BODY_TOO_BIG = 58,
    LISP65_ERR_LCC_INVALID_PARAMETER_LIST = 59,
    LISP65_ERR_VM_PRIMITIVE_NOT_DESIGNATOR = 60,
    LISP65_ERROR_CODE_LIMIT = 61
};

/* Only the shipped MEGA65 overlay profile removes static text from Bank 0. */
#if defined(__MEGA65__) && defined(LISP65_RUNTIME_OVERLAY)
#define LISP65_NUMERIC_ERRORS 1
#endif

/* Link-only product evidence. The empty-flags section has address zero and is
 * absent from the PRG; LTO removes markers together with unreachable origins. */
#if defined(LISP65_NUMERIC_ERRORS) && defined(__mos__)
#define LISP65_ERROR_EMISSION_MARK(code) \
    __asm__ volatile( \
        ".pushsection .lisp65_error_callsites,\"\",@progbits\n" \
        ".byte %c0\n" \
        ".popsection" :: "i"(code))
#else
#define LISP65_ERROR_EMISSION_MARK(code) ((void)0)
#endif

#endif /* LISP65_ERROR_CODES_H */
