/* Generated by tools/host-lisp/v2_native_function_registry.py. */
#ifndef LISP65_V2_NATIVE_FUNCTION_DISPATCH_H
#define LISP65_V2_NATIVE_FUNCTION_DISPATCH_H

#define LISP65_V2_NATIVE_FUNCTION_COUNT 39
#define LISP65_V2_NATIVE_FUNCTION_EXCLUSION_COUNT 34
#define LISP65_V2_NATIVE_KIND_FOLD_IDENTITY 1
#define LISP65_V2_NATIVE_KIND_FOLD_REQUIRED 2
#define LISP65_V2_NATIVE_KIND_CALLPRIM 3
#define LISP65_V2_NATIVE_KIND_OPFN 4

#define LISP65_V2_CALLPRIM_ACTIVE_COUNT 57
#define LISP65_V2_CALLPRIM_ACTIVE_ROWS(X) \
    X("stringp", 0) \
    X("string-length", 3) \
    X("string-ref", 4) \
    X("symbolp", 5) \
    X("numberp", 6) \
    X("apply", 7) \
    X("funcall", 8) \
    X("screen-size", 9) \
    X("screen-clear", 10) \
    X("screen-put-char", 11) \
    X("screen-write-string", 12) \
    X("read-key", 13) \
    X("poll-key", 14) \
    X("%disk-read-sector", 15) \
    X("%disk-byte", 16) \
    X("%disk-load-file", 17) \
    X("%disk-load-lib", 18) \
    X("symbol-value", 19) \
    X("set-symbol-value", 20) \
    X("%disk-poke", 21) \
    X("%disk-write-sector", 22) \
    X("nreverse", 23) \
    X("rplaca", 24) \
    X("rplacd", 25) \
    X("%string-codes", 28) \
    X("%string-from-codes", 29) \
    X("%cs-read-open", 30) \
    X("%fasl-read-form", 31) \
    X("%fasl-stage", 32) \
    X("%fasl-stage-get", 33) \
    X("%set-macro", 35) \
    X("function-kind", 36) \
    X("gensym", 37) \
    X("lcc-install", 38) \
    X("macroexpand-1", 39) \
    X("prin1", 41) \
    X("symbol-count", 42) \
    X("symbol-max", 43) \
    X("symbol-name", 44) \
    X("write-char", 45) \
    X("%fasl-error-entries-overflow", 46) \
    X("%fasl-error-nodes-overflow", 47) \
    X("%fasl-error-not-a-defun", 48) \
    X("%fasl-error-output-overflow", 49) \
    X("%fasl-error-patches-overflow", 50) \
    X("%fasl-error-strings-overflow", 51) \
    X("%fasl-error-too-many-helpers", 52) \
    X("%fasl-error-unsupported-literal", 53) \
    X("%fasl-error-window-overflow", 54) \
    X("%lcc-error-do-body-too-big", 55) \
    X("%lcc-error-invalid-parameter-list", 56) \
    X("boundp", 57) \
    X("%list-malformed-error", 58) \
    X("set", 59) \
    X("key-event", 60) \
    X("peek", 61) \
    X("poke", 62)

#define LISP65_V2_NATIVE_FUNCTION_TREE_ROWS(X) \
    X(P_ADD, 1, OP_ADD) \
    X(P_MUL, 1, OP_MUL) \
    X(P_SUB, 2, OP_SUB) \
    X(P_DIV, 2, OP_DIV) \
    X(P_CAR, 4, 1) \
    X(P_CDR, 4, 2) \
    X(P_CONSP, 4, 3) \
    X(P_CONS, 4, 5) \
    X(P_EQ, 4, 6) \
    X(P_EQL, 4, 6) \
    X(P_NUMEQ, 4, 6) \
    X(P_LT, 4, 7) \
    X(P_GT, 4, 8) \
    X(P_MOD, 4, 10) \
    X(P_LE, 4, 11) \
    X(P_GE, 4, 12) \
    X(P_STRINGP, 3, 0) \
    X(P_STRLEN, 3, 3) \
    X(P_STRREF, 3, 4) \
    X(P_SYMBOLP, 3, 5) \
    X(P_NUMBERP, 3, 6) \
    X(P_APPLY, 3, 7) \
    X(P_FUNCALL, 3, 8) \
    X(P_SCRSIZE, 3, 9) \
    X(P_SCRCLEAR, 3, 10) \
    X(P_SCRPUT, 3, 11) \
    X(P_SCRWRITE, 3, 12) \
    X(P_SYMVAL, 3, 19) \
    X(P_NREVERSE, 3, 23) \
    X(P_RPLACA, 3, 24) \
    X(P_RPLACD, 3, 25) \
    X(P_GENSYM, 3, 37) \
    X(P_PRIN1, 3, 41) \
    X(P_WRITECHAR, 3, 45) \
    X(P_BOUNDP, 3, 57) \
    X(P_SET, 3, 59) \
    X(P_KEYEVENT, 3, 60) \
    X(P_PEEK, 3, 61) \
    X(P_POKE, 3, 62)

#define LISP65_V2_NATIVE_FUNCTION_INTRINSIC_ALIAS_COUNT 2
#define LISP65_V2_NATIVE_FUNCTION_INTRINSIC_ALIAS_ROWS(X) \
    X("not", 4) \
    X("null", 4)

#define LISP65_V2_NATIVE_FUNCTION_FOLD_IDENTITY_COUNT 2
#define LISP65_V2_NATIVE_FUNCTION_FOLD_IDENTITY_ROWS(X) \
    X("+", OP_ADD) \
    X("*", OP_MUL)
#define LISP65_V2_NATIVE_FUNCTION_FOLD_IDENTITY_MATCH(sym) (((sym) == intern("+")) || ((sym) == intern("*")))
#define LISP65_V2_NATIVE_FUNCTION_FOLD_IDENTITY_VALUE(sym) (((sym) == intern("+") ? OP_ADD : OP_MUL))

#define LISP65_V2_NATIVE_FUNCTION_FOLD_REQUIRED_COUNT 2
#define LISP65_V2_NATIVE_FUNCTION_FOLD_REQUIRED_ROWS(X) \
    X("-", OP_SUB) \
    X("/", OP_DIV)
#define LISP65_V2_NATIVE_FUNCTION_FOLD_REQUIRED_MATCH(sym) (((sym) == intern("-")) || ((sym) == intern("/")))
#define LISP65_V2_NATIVE_FUNCTION_FOLD_REQUIRED_VALUE(sym) (((sym) == intern("-") ? OP_SUB : OP_DIV))

#define LISP65_V2_NATIVE_FUNCTION_CALLPRIM_COUNT 23
#define LISP65_V2_NATIVE_FUNCTION_CALLPRIM_ROWS(X) \
    X("stringp", 0) \
    X("string-length", 3) \
    X("string-ref", 4) \
    X("symbolp", 5) \
    X("numberp", 6) \
    X("apply", 7) \
    X("funcall", 8) \
    X("screen-size", 9) \
    X("screen-clear", 10) \
    X("screen-put-char", 11) \
    X("screen-write-string", 12) \
    X("symbol-value", 19) \
    X("nreverse", 23) \
    X("rplaca", 24) \
    X("rplacd", 25) \
    X("gensym", 37) \
    X("prin1", 41) \
    X("write-char", 45) \
    X("boundp", 57) \
    X("set", 59) \
    X("key-event", 60) \
    X("peek", 61) \
    X("poke", 62)

#define LISP65_V2_NATIVE_FUNCTION_OPFN_COUNT 12
#define LISP65_V2_NATIVE_FUNCTION_OPFN_ROWS(X) \
    X("car", 1) \
    X("cdr", 2) \
    X("consp", 3) \
    X("cons", 5) \
    X("eq", 6) \
    X("eql", 6) \
    X("=", 6) \
    X("<", 7) \
    X(">", 8) \
    X("mod", 10) \
    X("<=", 11) \
    X(">=", 12)

#define LISP65_V2_NATIVE_FUNCTION_BOUNDP_COUNT 0
#define LISP65_V2_NATIVE_FUNCTION_BOUNDP_ROWS(X)

#define LISP65_V2_NATIVE_FUNCTION_EXCLUSION_COUNT 34
#define LISP65_V2_NATIVE_FUNCTION_EXCLUSION_ROWS(X) \
    X("read-key", 13) \
    X("poll-key", 14) \
    X("%disk-read-sector", 15) \
    X("%disk-byte", 16) \
    X("%disk-load-file", 17) \
    X("%disk-load-lib", 18) \
    X("set-symbol-value", 20) \
    X("%disk-poke", 21) \
    X("%disk-write-sector", 22) \
    X("%string-codes", 28) \
    X("%string-from-codes", 29) \
    X("%cs-read-open", 30) \
    X("%fasl-read-form", 31) \
    X("%fasl-stage", 32) \
    X("%fasl-stage-get", 33) \
    X("%set-macro", 35) \
    X("function-kind", 36) \
    X("lcc-install", 38) \
    X("macroexpand-1", 39) \
    X("symbol-count", 42) \
    X("symbol-max", 43) \
    X("symbol-name", 44) \
    X("%fasl-error-entries-overflow", 46) \
    X("%fasl-error-nodes-overflow", 47) \
    X("%fasl-error-not-a-defun", 48) \
    X("%fasl-error-output-overflow", 49) \
    X("%fasl-error-patches-overflow", 50) \
    X("%fasl-error-strings-overflow", 51) \
    X("%fasl-error-too-many-helpers", 52) \
    X("%fasl-error-unsupported-literal", 53) \
    X("%fasl-error-window-overflow", 54) \
    X("%lcc-error-do-body-too-big", 55) \
    X("%lcc-error-invalid-parameter-list", 56) \
    X("%list-malformed-error", 58)

#endif
