#!/usr/bin/env python3
"""Emit C fixtures from lisp65 P0 golden bytecode vectors."""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bytecode_p0 as B  # noqa: E402
import bytecode_p0_compiler as C  # noqa: E402


K_FIX = 1
K_NIL = 2
K_T = 3
K_SYMBOL = 4
K_CONS = 5
K_LIST = 6
K_STRING = 7


def _cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _bytes_initializer(data):
    return ", ".join("0x%02x" % b for b in data)


class ArgPool:
    def __init__(self):
        self.nodes = []
        self.index = []

    def add(self, spec):
        if spec is None:
            return self._node(K_NIL)
        if isinstance(spec, bool):
            return self._node(K_T if spec else K_NIL)
        if isinstance(spec, int):
            return self._node(K_FIX, value=spec)
        if isinstance(spec, str):
            if spec.lower() == "nil":
                return self._node(K_NIL)
            if spec.lower() == "t":
                return self._node(K_T)
            raise ValueError("string args must use {'symbol': name}: %r" % spec)
        if isinstance(spec, list):
            children = [self.add(item) for item in spec]
            first = len(self.index)
            self.index.extend(children)
            return self._node(K_LIST, first=first, count=len(children))
        if isinstance(spec, dict):
            if "symbol" in spec:
                return self._node(K_SYMBOL, name=spec["symbol"])
            if "string" in spec:
                children = [self.add(ord(ch)) for ch in spec["string"]]
                first = len(self.index)
                self.index.extend(children)
                return self._node(K_STRING, first=first, count=len(children))
            if "cons" in spec:
                a, b = spec["cons"]
                first = len(self.index)
                self.index.extend([self.add(a), self.add(b)])
                return self._node(K_CONS, first=first, count=2)
        raise ValueError("unsupported arg spec: %r" % (spec,))

    def add_arg_list(self, specs):
        nodes = [self.add(spec) for spec in specs]
        first = len(self.index)
        self.index.extend(nodes)
        return first, len(specs)

    def _node(self, kind, value=0, first=0, count=0, name=None):
        idx = len(self.nodes)
        self.nodes.append(
            {
                "kind": kind,
                "value": int(value),
                "first": int(first),
                "count": int(count),
                "name": name,
            }
        )
        return idx


def _load(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if data.get("format") != "lisp65-bytecode-p0-golden-vectors-v1":
        raise ValueError("unexpected vector format in %s" % path)
    return data


def _native_vm_omission(vector):
    omission = vector.get("native_c_vm")
    if omission is None:
        return None
    if not isinstance(omission, dict) or set(omission) != {"status", "reason"}:
        raise ValueError(
            "%s: native_c_vm must contain exactly status and reason" % vector.get("name")
        )
    if omission["status"] != "omitted":
        raise ValueError("%s: native_c_vm status must be omitted" % vector.get("name"))
    if not isinstance(omission["reason"], str) or not omission["reason"].strip():
        raise ValueError("%s: native_c_vm omission needs a reason" % vector.get("name"))
    return omission["reason"].strip()


def emit_header(data, out):
    pool = ArgPool()
    omissions = [
        (vector["name"], reason)
        for vector in data["vectors"]
        for reason in [_native_vm_omission(vector)]
        if reason is not None
    ]
    vectors = [
        v for v in data["vectors"]
        if not v.get("expect_compile_error") and _native_vm_omission(v) is None
    ]
    symbols = data.get("symbols", [])
    code_names = []
    meta = []
    max_code_len = max(len(B.parse_hex(v["code_object_hex"])) for v in vectors)

    print("/* generated by tools/host-lisp/bytecode_p0_c_vectors.py; do not edit */", file=out)
    print("#ifndef LISP65_BYTECODE_P0_C_VECTORS_H", file=out)
    print("#define LISP65_BYTECODE_P0_C_VECTORS_H", file=out)
    print("#include <stdint.h>", file=out)
    print("", file=out)
    print("#define BC_ARG_FIX 1", file=out)
    print("#define BC_ARG_NIL 2", file=out)
    print("#define BC_ARG_T 3", file=out)
    print("#define BC_ARG_SYMBOL 4", file=out)
    print("#define BC_ARG_CONS 5", file=out)
    print("#define BC_ARG_LIST 6", file=out)
    print("#define BC_ARG_STRING 7", file=out)
    print("", file=out)
    print("typedef struct {", file=out)
    print("    uint8_t kind;", file=out)
    print("    int16_t value;", file=out)
    print("    uint16_t first;", file=out)
    print("    uint16_t count;", file=out)
    print("    const char *name;", file=out)
    print("} bc_p0_arg_node;", file=out)
    print("", file=out)
    print("typedef struct {", file=out)
    print("    const char *name;", file=out)
    print("    const uint8_t *code;", file=out)
    print("    uint16_t code_len;", file=out)
    print("    uint16_t arg_first;", file=out)
    print("    uint8_t argc;", file=out)
    print("    uint16_t lit_first;", file=out)
    print("    uint8_t nlits;", file=out)
    print("    uint16_t expect_node;", file=out)
    print("    const char *entry;", file=out)
    print("} bc_p0_vector;", file=out)
    print("", file=out)

    print("typedef struct { const char *name; const char *reason; } bc_p0_omission;", file=out)
    print("static const bc_p0_omission bc_p0_omissions[] = {", file=out)
    for name, reason in omissions:
        print("    { %s, %s }," % (_cstr(name), _cstr(reason)), file=out)
    print("};", file=out)
    print("#define BC_P0_OMISSION_COUNT %d" % len(omissions), file=out)
    print("", file=out)

    print("static const char *const bc_p0_global_symbols[] = {", file=out)
    for sym in symbols:
        print("    %s," % _cstr(sym), file=out)
    print("};", file=out)
    print("#define BC_P0_GLOBAL_SYMBOL_COUNT %d" % len(symbols), file=out)
    print("#define BC_P0_MAX_CODE_LEN %d" % max_code_len, file=out)
    print("", file=out)

    for i, vector in enumerate(vectors):
        code = B.parse_hex(vector["code_object_hex"])
        name = "bc_p0_code_%d" % i
        code_names.append(name)
        print("static const uint8_t %s[] = { %s };" % (name, _bytes_initializer(code)), file=out)
        arg_first, argc = pool.add_arg_list(vector.get("args", []))
        lit_first, nlits = pool.add_arg_list(vector["code"].get("literals", []))
        expect_node = pool.add(_expect_spec(vector["expect"]))
        meta.append((vector, arg_first, argc, lit_first, nlits, expect_node))
    print("", file=out)

    print("static const uint16_t bc_p0_arg_index[] = {", file=out)
    if pool.index:
        print("    %s" % ", ".join(str(i) for i in pool.index), file=out)
    print("};", file=out)
    print("", file=out)

    print("static const bc_p0_arg_node bc_p0_arg_nodes[] = {", file=out)
    for node in pool.nodes:
        name = "0" if node["name"] is None else _cstr(node["name"])
        print(
            "    { %d, %d, %d, %d, %s },"
            % (node["kind"], node["value"], node["first"], node["count"], name),
            file=out,
        )
    print("};", file=out)
    print("", file=out)

    print("static const bc_p0_vector bc_p0_vectors[] = {", file=out)
    for i, (vector, arg_first, argc, lit_first, nlits, expect_node) in enumerate(meta):
        entry = vector.get("entry")
        print(
            "    { %s, %s, sizeof(%s), %d, %d, %d, %d, %d, %s },"
            % (
                _cstr(vector["name"]),
                code_names[i],
                code_names[i],
                arg_first,
                argc,
                lit_first,
                nlits,
                expect_node,
                "0" if entry is None else _cstr(entry),
            ),
            file=out,
        )
    print("};", file=out)
    print("#define BC_P0_VECTOR_COUNT %d" % len(vectors), file=out)
    print("", file=out)
    print("#endif", file=out)


def _expect_spec(text):
    if text == "nil":
        return None
    if text == "t":
        return True
    try:
        return int(text, 10)
    except ValueError:
        return _form_to_spec(C.parse_one(text))


def _form_to_spec(form):
    if form == "nil":
        return None
    if form == "t":
        return True
    if isinstance(form, int):
        return form
    if isinstance(form, str):
        return {"symbol": form}
    if isinstance(form, C.StringLit):
        return {"string": form.value}
    if isinstance(form, C.DottedList):
        out = _form_to_spec(form.tail)
        for item in reversed(form.items):
            out = {"cons": [_form_to_spec(item), out]}
        return out
    if isinstance(form, list):
        return [_form_to_spec(item) for item in form]
    raise ValueError("unsupported expected form: %r" % (form,))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path")
    ns = ap.parse_args(argv)
    emit_header(_load(ns.json_path), sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
