#!/usr/bin/env python3
"""Generate vectors, run the independent C decoder and perform a real MOS link."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "host-lisp"))

import c2_direct_oracles as O  # noqa: E402
import c2_direct_proof as D  # noqa: E402


BUILD = ROOT / "build" / "c2-direct-target"
HEADER = BUILD / "c2-direct-vectors.h"
HOST_BIN = BUILD / "c2-direct-host"
TARGET_PRG = BUILD / "c2-direct-target.prg"
TARGET_ELF = BUILD / "c2-direct-target.prg.elf"
TARGET_MAP = BUILD / "c2-direct-target.map"
RECEIPT = ROOT / (
    "tests/bytecode/dialect-v2/evidence/architecture-blocks/"
    "c2.1-direct-target-link-receipt.json"
)
SOURCE = ROOT / "scripts" / "c2-direct-target-main.c"
CC = ROOT / "tools" / "llvm-mos" / "bin" / "mos-mega65-clang"
SIZE = ROOT / "tools" / "llvm-mos" / "bin" / "llvm-size"
NM = ROOT / "tools" / "llvm-mos" / "bin" / "llvm-nm"


class TargetError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise TargetError(message)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def binding(path: Path) -> dict[str, Any]:
    return {"path": str(path.relative_to(ROOT)), "bytes": path.stat().st_size, "sha256": sha(path)}


def run(argv: list[str], *, timeout: int = 60) -> subprocess.CompletedProcess[str]:
    process = subprocess.run(
        argv, cwd=ROOT, capture_output=True, text=True, timeout=timeout, check=False
    )
    if process.returncode != 0:
        raise TargetError(
            "%s failed (%d): %s" % (Path(argv[0]).name, process.returncode,
                                      (process.stderr or process.stdout).strip())
        )
    return process


def generate_header() -> bytes:
    target, code, metadata = O.target_inputs()
    shelf = O.build_shelf(target, code, metadata)
    lines = [
        "/* generated by tools/host-lisp/c2_direct_target.py; do not edit */",
        "#ifndef LISP65_C2_DIRECT_VECTORS_H",
        "#define LISP65_C2_DIRECT_VECTORS_H",
        "#include <stdint.h>",
        "#define C2_DIRECT_SHELF_BYTES %du" % len(shelf),
        "static const uint8_t c2_direct_shelf[C2_DIRECT_SHELF_BYTES] = {",
    ]
    for offset in range(0, len(shelf), 16):
        lines.append("  " + ", ".join("0x%02x" % b for b in shelf[offset:offset + 16]) + ",")
    lines.extend(("};", "#endif", ""))
    return "\n".join(lines).encode("ascii")


def parse_size(text: str) -> dict[str, int]:
    lines = [line.split() for line in text.splitlines() if line.strip()]
    require(len(lines) >= 2 and lines[0][:4] == ["text", "data", "bss", "dec"],
            "llvm-size output drift")
    row = lines[-1]
    return {"text": int(row[0]), "data": int(row[1]), "bss": int(row[2]), "dec": int(row[3])}


def parse_symbols(text: str) -> dict[str, int]:
    wanted = {"proof_run", "decode_shelf", "decode_metadata", "run_entry", "c2_direct_shelf"}
    result: dict[str, int] = {}
    for line in text.splitlines():
        fields = line.split()
        if len(fields) >= 4 and fields[-1] in wanted:
            result[fields[-1]] = int(fields[1], 16)
    require(set(result) == wanted, "target proof symbol-size inventory drift")
    return result


def render() -> dict[str, Any]:
    BUILD.mkdir(parents=True, exist_ok=True)
    HEADER.write_bytes(generate_header())
    host = run([
        "cc", "-std=c99", "-Os", "-Wall", "-Wextra", "-Werror",
        "-I", str(BUILD), str(SOURCE), "-o", str(HOST_BIN),
    ])
    require(not host.stdout and not host.stderr, "host compiler emitted diagnostics")
    host_run = run([str(HOST_BIN)])
    match = re.fullmatch(
        r"c2-direct-target: PASS routes=5 entries=6 refills=(\d+) steps=(\d+) sink=(\d+)\n?",
        host_run.stdout,
    )
    require(match is not None and not host_run.stderr, "host target output drift")

    require(CC.is_file(), "pinned mos-mega65-clang missing")
    target_link = run([
        str(CC), "-std=c99", "-Os", "-flto", "-DC2_TARGET_LINK_ONLY",
        "-I", str(BUILD), str(SOURCE), "-Wl,-Map," + str(TARGET_MAP),
        "-o", str(TARGET_PRG),
    ], timeout=120)
    require(not target_link.stdout and not target_link.stderr, "target linker emitted diagnostics")
    require(TARGET_ELF.is_file(), "llvm-mos companion ELF missing")
    sizes = parse_size(run([str(SIZE), str(TARGET_ELF)]).stdout)
    symbols = run([str(NM), "--print-size", "--size-sort", "--radix=x", str(TARGET_ELF)]).stdout
    require(" proof_run" in symbols and " c2_direct_shelf" in symbols,
            "target link stripped proof decoder or shelf")
    symbol_bytes = parse_symbols(symbols)
    return {
        "format": "lisp65-c2.1-direct-target-link-receipt-v1",
        "version": 1,
        "recorded_on": "2026-07-19",
        "status": "independent-c-proof-subset-host-passed-mos-link-passed-not-device-run",
        "claim_limit": (
            "This receipt proves an independent self-describing C decoder/executor for the "
            "anonymous-helper proof subset on the host and a real llvm-mos MEGA65 link of "
            "the same source. It is not the complete product decoder. The MOS artifact was "
            "not run on a device; it proves no Enhanced-DMA timing, hardware reset, product "
            "fit or product behavior."
        ),
        "bindings": {
            "target": binding(D.TARGET),
            "direct_proof_receipt": binding(D.RECEIPT),
            "negative_reset_receipt": binding(O.RECEIPT),
            "c_source": binding(SOURCE),
            "orchestrator": binding(Path(__file__)),
            "compiler": binding(ROOT / "tools/llvm-mos/bin/clang-23"),
        },
        "generated_vector": binding(HEADER),
        "host_execution": {
            "routes": 5,
            "entries": 6,
            "window_refills": int(match.group(1)),
            "steps": int(match.group(2)),
            "sink": int(match.group(3)),
            "binary": binding(HOST_BIN),
        },
        "target_link": {
            "artifact": binding(TARGET_PRG),
            "elf": binding(TARGET_ELF),
            "map": binding(TARGET_MAP),
            "sizes": sizes,
            "symbol_bytes": symbol_bytes,
            "catalog_record_count": "decoded-from-header-not-compiled-as-one",
            "decoder_symbol_retained": True,
            "shelf_symbol_retained": True,
            "device_execution": "not-run",
        },
        "capacity_delta": {
            "scope": "standalone-proof-artifact-only",
            "product_bytes": 0,
            "bank0": "not-integrated-not-measured",
            "ext": "not-integrated-not-measured",
            "fixed_overlay": "not-integrated-not-measured",
            "runtime_overlay_bank": "not-integrated-not-measured",
            "resident_island": "not-integrated-not-measured",
            "installer_slice": "not-integrated-not-measured",
        },
        "next_authorized_action": (
            "Measure one isolated product-layout substitution probe, including every frozen "
            "capacity dimension and refill latency; stop for review before any debit or product cut."
        ),
    }


def canonical(value: dict[str, Any]) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def selftest() -> None:
    first = generate_header()
    second = generate_header()
    require(first == second and b"C2_DIRECT_SHELF_BYTES 319u" in first,
            "C target vector generation drift")
    mutated = bytearray(first)
    mutated[-2] ^= 1
    require(bytes(mutated) != first, "target vector mutation ineffective")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("write", "check", "selftest"))
    args = parser.parse_args()
    try:
        if args.action == "selftest":
            selftest()
            print("c2-direct-target: SELFTEST PASS vectors=2/2 mutation=1")
            return 0
        value = render()
        data = canonical(value)
        if args.action == "write":
            RECEIPT.parent.mkdir(parents=True, exist_ok=True)
            RECEIPT.write_bytes(data)
            action = "WROTE"
        else:
            require(RECEIPT.is_file() and RECEIPT.read_bytes() == data,
                    "pinned C2 target receipt drift")
            action = "PASS"
        print(
            "c2-direct-target: %s host=5/5 mos-bytes=%d device=not-run"
            % (action, value["target_link"]["artifact"]["bytes"])
        )
        return 0
    except (OSError, ValueError, subprocess.SubprocessError, TargetError) as exc:
        print("c2-direct-target: FAIL: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
