#!/usr/bin/env python3
"""Run and llvm-mos-link an independent compact C2I-v2/C2D-v1 decoder."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/host-lisp"))
import c2_full_emission as F  # noqa: E402

BUILD = ROOT / "build/c2-full-target"
HEADER = BUILD / "c2-full-vectors.h"
HOST_BIN = BUILD / "c2-full-host"
TARGET_PRG = BUILD / "c2-full-target.prg"
TARGET_ELF = BUILD / "c2-full-target.prg.elf"
TARGET_MAP = BUILD / "c2-full-target.map"
SOURCE = ROOT / "scripts/c2-full-target-main.c"
RECEIPT = ROOT / (
    "tests/bytecode/dialect-v2/evidence/architecture-blocks/"
    "c2.1-full-target-link-receipt.json"
)
FULL_RECEIPT = ROOT / (
    "tests/bytecode/dialect-v2/evidence/architecture-blocks/"
    "c2.1-full-emission-receipt.json"
)
CC = ROOT / "tools/llvm-mos/bin/mos-mega65-clang"
SIZE = ROOT / "tools/llvm-mos/bin/llvm-size"
NM = ROOT / "tools/llvm-mos/bin/llvm-nm"


class TargetError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise TargetError(message)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def bind(path: Path) -> dict[str, Any]:
    data = path.read_bytes()
    return {"path": path.relative_to(ROOT).as_posix(), "bytes": len(data), "sha256": sha(data)}


def run(argv: list[str], timeout: int = 120) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True,
                            timeout=timeout, check=False)
    if result.returncode:
        raise TargetError("%s failed (%d): %s" %
                          (Path(argv[0]).name, result.returncode,
                           (result.stderr or result.stdout).strip()))
    return result


def compact_vectors() -> tuple[bytes, bytes]:
    pool = b"\x06\x00shared"
    desc = [F.Desc(F.K_NIL), F.Desc(F.K_SYMBOL, 6, 0),
            F.Desc(F.K_PAIR, 1, 0), F.Desc(F.K_PAIR, 1, 2)]
    code = b"\xb5\x00\x00\x02\x00\x00\x00"
    pack = __import__("struct").pack
    entry_record = F.p24(0) + pack("<HHB", len(code), 4, 0)
    entry_record += pack("<HBBHH", 0xffff, 0, 0, 0, 0)
    require(len(entry_record) == 16, "compact entry width drift")
    header = bytearray(b"C2I\0")
    header += bytes((2, 24, 16, 8))
    header += pack("<HHHHHHHH", 0, 1, 4, 24, 40, 72, len(pool), 0)
    metadata = bytes(header) + entry_record + b"".join(item.encode() for item in desc) + pool
    if len(metadata) & 1:
        metadata += b"\0"
    image = F.Emitted("proof", "proof", F.CONTRACT, {"entries": [{"length": len(code)}]}, code,
                      metadata, desc, {}, [4], 2, {kind: 0 for kind in range(9)}, 0)
    shelf, rows, crc = F.build_shelf([image])
    c2d = F.build_c2d([image], rows, crc)
    F.verify_shelf(shelf, [image], set())
    facts = F.decode_c2d(c2d, [image], rows, crc)
    require(facts == {"images": 1, "entries": 1, "resolutions": 4,
                      "bytes": 70, "headroom": 50746}, "compact C2D drift")
    return shelf, c2d


def array(name: str, data: bytes) -> list[str]:
    result = [f"#define {name.upper()}_BYTES {len(data)}u",
              f"static const uint8_t {name}[{name.upper()}_BYTES] = {{"]
    for at in range(0, len(data), 16):
        result.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[at:at + 16]) + ",")
    result.append("};")
    return result


def header_bytes() -> bytes:
    shelf, c2d = compact_vectors()
    lines = ["/* generated by tools/host-lisp/c2_full_target.py; do not edit */",
             "#ifndef LISP65_C2_FULL_VECTORS_H", "#define LISP65_C2_FULL_VECTORS_H",
             "#include <stdint.h>"]
    lines += array("c2_full_shelf", shelf)
    lines += array("c2_full_c2d", c2d)
    lines += ["#endif", ""]
    return "\n".join(lines).encode("ascii")


def parse_size(text: str) -> dict[str, int]:
    rows = [line.split() for line in text.splitlines() if line.strip()]
    require(len(rows) >= 2 and rows[0][:4] == ["text", "data", "bss", "dec"],
            "llvm-size output drift")
    row = rows[-1]
    return {"text": int(row[0]), "data": int(row[1]), "bss": int(row[2]), "dec": int(row[3])}


def symbol_sizes(text: str) -> dict[str, int]:
    wanted = {"proof_run", "decode_shelf", "decode_c2i_v2", "decode_c2d",
              "c2_full_shelf"}
    result: dict[str, int] = {}
    for line in text.splitlines():
        fields = line.split()
        if len(fields) >= 4 and fields[-1] in wanted:
            result[fields[-1]] = int(fields[1], 16)
    require(set(result) == wanted, "full target symbol inventory drift")
    return result


def render() -> dict[str, Any]:
    full = json.loads(FULL_RECEIPT.read_text(encoding="utf-8"))
    require(full["status"] == "host-emission-and-decode-passed-product-link-not-run"
            and full["facts"]["c2i_v2_descriptors"] == 2249,
            "complete host-emission receipt missing")
    BUILD.mkdir(parents=True, exist_ok=True)
    HEADER.write_bytes(header_bytes())
    host = run(["cc", "-std=c99", "-Os", "-Wall", "-Wextra", "-Werror",
                "-I", str(BUILD), str(SOURCE), "-o", str(HOST_BIN)])
    require(not host.stdout and not host.stderr, "host compiler diagnostics")
    execution = run([str(HOST_BIN)])
    match = re.fullmatch(r"c2-full-target: PASS entries=1 descriptors=4 depth=2 c2d=70 sink=(\d+)\n?",
                         execution.stdout)
    require(match is not None and not execution.stderr, "full target execution drift")
    target = run([str(CC), "-std=c99", "-Os", "-flto", "-DC2_TARGET_LINK_ONLY",
                  "-I", str(BUILD), str(SOURCE), "-Wl,-Map," + str(TARGET_MAP),
                  "-o", str(TARGET_PRG)])
    require(not target.stdout and not target.stderr and TARGET_ELF.is_file(),
            "MOS full target link diagnostics/artifact")
    sizes = parse_size(run([str(SIZE), str(TARGET_ELF)]).stdout)
    symbols = symbol_sizes(run([str(NM), "--print-size", "--size-sort", "--radix=x",
                                str(TARGET_ELF)]).stdout)
    return {
        "format": "lisp65-c2.1-full-target-link-receipt-v1",
        "version": 1,
        "recorded_on": "2026-07-19",
        "status": "independent-c2i-v2-c2d-v1-host-passed-mos-linked-not-device-run",
        "claim_limit": (
            "This receipt proves an independent C decoder for a compact contract-derived "
            "C2I-v2 kind-8/backward-pair/sharing vector, L65S-v4-direct and C2D-v1 on "
            "the host, plus a real llvm-mos link. The complete six-image geometry remains "
            "bound by the host-emission receipt. This is not a product link, capacity "
            "authorization or device execution claim."
        ),
        "bindings": {"full_emission": bind(FULL_RECEIPT), "contract": bind(F.CONTRACT),
                     "source": bind(SOURCE), "orchestrator": bind(Path(__file__)),
                     "compiler": bind(ROOT / "tools/llvm-mos/bin/clang-23")},
        "generated_vector": bind(HEADER),
        "host_execution": {"entries": 1, "descriptors": 4, "maximum_pair_depth": 2,
                           "c2d_bytes": 70, "sink": int(match.group(1)),
                           "binary": bind(HOST_BIN)},
        "target_link": {"artifact": bind(TARGET_PRG), "elf": bind(TARGET_ELF),
                        "map": bind(TARGET_MAP), "sizes": sizes,
                        "symbol_bytes": symbols, "device_execution": "not-run"},
        "capacity_delta": {"scope": "standalone-proof-artifact-only",
                           "product_bytes": 0, "bank0": "not-integrated-not-measured",
                           "ext": "not-integrated-not-measured", "fixed_overlay": "not-integrated-not-measured",
                           "runtime_overlay_bank": "not-integrated-not-measured",
                           "resident_island": "not-integrated-not-measured", "installer_slice": "not-integrated-not-measured"},
        "next_action": "Real product-layout substitution link with every capacity dimension",
    }


def canonical(value: dict[str, Any]) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def selftest() -> None:
    first, second = header_bytes(), header_bytes()
    require(first == second and b"C2_FULL_C2D_BYTES 70u" in first,
            "full target vector determinism")
    bad = bytearray(first); bad[-2] ^= 1
    require(bytes(bad) != first, "full target vector mutation ineffective")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("write", "check", "selftest"))
    args = parser.parse_args()
    try:
        if args.action == "selftest":
            selftest(); print("c2-full-target: SELFTEST PASS vectors=2/2 mutation=1"); return 0
        value = render(); data = canonical(value)
        if args.action == "write":
            RECEIPT.parent.mkdir(parents=True, exist_ok=True); RECEIPT.write_bytes(data); verb = "WROTE"
        else:
            require(RECEIPT.is_file() and RECEIPT.read_bytes() == data,
                    "C2 full-target receipt drift; regenerate with write"); verb = "PASS"
        print(f"c2-full-target: {verb} host=4/4 mos-bytes={value['target_link']['artifact']['bytes']} device=not-run")
        return 0
    except (OSError, ValueError, subprocess.SubprocessError, TargetError, F.FullError) as error:
        print(f"c2-full-target: FAIL: {error}", file=sys.stderr); return 1


if __name__ == "__main__":
    raise SystemExit(main())
