#!/usr/bin/env python3
"""Generate private inline-only Lisp constants for the v1.4 m65-hw pilot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "config/c2-m65-hw-contract.json"
OUTPUT = ROOT / "lib/m65-hw-registers.lisp"


def generated_text() -> str:
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    registers = contract["registers"]
    lines = [
        "; Generated by tools/host-lisp/c2_m65_hw_registers.py.",
        "; Do not edit: config/c2-m65-hw-contract.json is the address authority.",
        "",
    ]
    for name, raw in registers.items():
        value = int(raw, 0)
        macro = "%m65-reg-" + name.replace("_", "-")
        lines.append(f"(defun {macro}-hi () {value >> 8})")
        lines.append(f"(defun {macro}-lo () {value & 0xff})")
    lines.extend([
        "(defun %m65-sprite-shape-slot-hi () 23)",
        "(defun %m65-sprite-shape-slot-lo () 192)",
        "(defun %m65-sprite-shape-pointer () 95)",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_text()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("c2-m65-hw-registers: FIRST RED: generated source drift")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    registers = json.loads(CONTRACT.read_text(encoding="utf-8"))["registers"]
    print(
        f"c2-m65-hw-registers: PASS registers={len(registers)} "
        f"output={OUTPUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
