#!/usr/bin/env python3
"""Pack-only dry-run adapter for Comfort default; never build a product.

All six L65I artifacts and index CRCs are regenerated from their manifests.
The inherited runtime/build-id is only a packing fixture, not a deliverable
2.5.0 image. A future accepted build must rebind every artifact to its build-id.
"""
import json
from pathlib import Path
import shutil
import subprocess
import sys

import comfort_library_medium as M
from comfort_default_producer import AUTH_PENDING, ROOT, HERE, PLANE, bind, write


def c1541(medium, *args):
    # c1541 can print PETSCII filenames; its diagnostic stream is not UTF-8.
    tool = shutil.which('c1541')
    assert tool, 'c1541 unavailable'
    result = subprocess.run([tool, str(medium), *args], cwd=ROOT,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert result.returncode == 0, result.stdout.decode('latin-1')


def main():
    if sys.argv[1:] != ['dry-run']:
        raise SystemExit('dry-run only')
    assert bind(M.ELF)['sha256'] == M.EXPECT['elf']
    assert bind(M.BASE)['sha256'] == M.EXPECT['d81']
    out = HERE / 'pack-dry-run'
    out.mkdir(exist_ok=True)
    medium = out / 'comfort-default-NOT-FOR-BOOT.d81'
    shutil.copyfile(M.BASE, medium)
    medium.chmod(0o644)
    before = M.D81.visible_files(M.BASE.read_bytes())
    libraries = json.loads(M.LIBRARIES.read_text())
    build_id = int(libraries['product_build_id'])
    base_artifacts = {r['name']: before[r['name'].upper().encode()] for r in libraries['libraries']}
    old_rows = M.L65I.decode_index(before[b'L65INDEX'], base_artifacts, artifact_build_id=build_id)
    specs = [(r['name'], r['shelf'], ROOT / r['manifest']['path'],
              tuple(old_rows[i]['dependencies'])) for i, r in enumerate(libraries['libraries'])]
    specs.append(('repl-comfort', 'repl', HERE / 'objects/repl-comfort.manifest.json', ()))
    payloads, provenance = {}, []
    for name, shelf, manifest, dependencies in specs:
        _, payload = M.F.measured_row(name, name, shelf, manifest, dependencies,
                                     1, 1, product_build_id=build_id)
        payloads[name] = payload
        artifact = out / (name + '.l65s')
        artifact.write_bytes(payload)
        if name in base_artifacts:
            assert payload == base_artifacts[name], name
        else:
            c1541(medium, '-write', str(artifact), name)
        provenance.append(dict(name=name, manifest=bind(manifest), artifact=bind(artifact)))
    init = PLANE / 'libraries/INIT.L65'
    c1541(medium, '-delete', 'init.l65')
    c1541(medium, '-write', str(init), 'init.l65')
    locators = M.L65I.d81_locators(medium)
    rows = []
    for name, shelf, manifest, dependencies in specs:
        row, payload = M.F.measured_row(name, name, shelf, manifest, dependencies,
                                       *locators[name], product_build_id=build_id)
        assert payload == payloads[name]
        rows.append(row)
    index = out / 'l65index'
    index.write_bytes(M.L65I.encode_index(rows))
    c1541(medium, '-delete', 'l65index')
    c1541(medium, '-write', str(index), 'l65index')
    raw = medium.read_bytes()
    M.D81.validate_bam(raw)
    after = M.D81.visible_files(raw)
    assert after[b'INIT.L65'] == init.read_bytes()
    assert after[b'L65INDEX'] == index.read_bytes()
    for name, payload in payloads.items():
        assert after[name.upper().encode()] == payload
    decoded = M.L65I.decode_index(after[b'L65INDEX'], payloads, artifact_build_id=build_id)
    assert decoded == rows
    changes = sorted(k.decode() for k in before if before[k] != after.get(k))
    assert changes == ['INIT.L65', 'L65INDEX'], changes
    assert set(after) - set(before) == {b'REPL-COMFORT'}
    mutations = M.L65I.mutation_gate(index.read_bytes(), payloads, artifact_build_id=build_id)
    files = {k.decode(): dict(bytes=len(v), sha256=M.hashlib.sha256(v).hexdigest())
             for k, v in sorted(after.items())}
    value = dict(status='PASS: PACK DRY-RUN ONLY; OLD RUNTIME, DO NOT BOOT',
                 AUTH_PENDING=AUTH_PENDING, product_build_id=build_id,
                 medium=bind(medium), base=bind(M.BASE), elf=bind(M.ELF),
                 index=bind(index), init=bind(init), packages=provenance,
                 rows=rows, mutations=mutations, changed_files=changes,
                 files=files, runtime_files_unchanged=True,
                 crc_rule='Each artifact decoded after build_extension; each row regenerated with measured_row; encode_index/decode_index and mutation_gate on readback. Boot-role bytes/CRCs unchanged because all runtime files are unchanged.',
                 pending='Future product identity and all boot-role/stager CRCs must be regenerated by the accepted producer after the price gate. This fixture is not successor native acceptance.')
    write(HERE / 'pack-dry-run.json', value)
    print(value['status'], value['medium']['sha256'])


if __name__ == '__main__':
    main()
