#!/usr/bin/env python3
"""Generate Comfort-private inline constants from the fixed linker owner."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[2]
OWNER = ROOT / "config/comfort-default-native/linker/full-map-linker/c.ld"
OUTPUT = ROOT / "lib/comfort-state-address.lisp"


def generated_text() -> str:
    matches = re.findall(
        r"^\.lisp65_comfort_state_bss (0x[0-9a-f]+) \(NOLOAD\)",
        OWNER.read_text(encoding="utf-8"), re.MULTILINE,
    )
    if len(matches) != 1:
        raise ValueError("expected one fixed Comfort high-BSS owner")
    address = int(matches[0], 16)
    if not 0 <= address <= 0xffff:
        raise ValueError("Comfort owner must fit the two-byte poke address")
    return "\n".join([
        "; Generated by tools/host-lisp/comfort_state_address.py.",
        "; Do not edit: config/comfort-default-native/linker/full-map-linker/c.ld is the address authority.",
        "",
        f"(defun %comfort-state-hi () {address >> 8})",
        f"(defun %comfort-state-lo () {address & 0xff})",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_text()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("comfort-state-address: FIRST RED: generated source drift")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    print(f"comfort-state-address: PASS output={OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
