"""Receipt-only boundaries for lost originals, authorized by b04cb21b.

These are NOT executed artifact witnesses. Future cards must measure again.
No manifest is read or regenerated by this checker.
"""
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import re
import sys

# Importing an era validator is a read, not permission to emit a pyc file.
sys.dont_write_bytecode = True

from terminal_ingress_artifacts import ArtifactError, read_only

ROOT = Path(__file__).resolve().parents[2]
ARCH = ROOT/'tests/bytecode/dialect-v2/evidence/architecture-blocks'
PINS = {
    'completion': ('post-v1.4 / Link-92 attribution (not release acceptance)',
                   'c2.3-post-v1.4-defstruct-completion-edge-receipt.json',
                   'a830d7fdb996fff11ec9f080cce9178592d9bc5bb9ec2d0effe45d7a2248bcbc'),
    'v110': ('v1.10 development/pricing (not release acceptance)', 'c2.3-v1.10-persistent-performance-receipt.json',
             '572e04874c7a71e2c5e55feaf729b7c4f920cc2fde980d74e385040388da2b67'),
    'tier1': ('2.0.0', 'c2.3-v2.0-domain-tier1-pricing-receipt.json',
              'aa5b866b8985865b7ee528853687b0ff20e55e02944bed9f6cf844c90834548f'),
}


def leaves(value, path=()):
    if isinstance(value, dict):
        for key, child in value.items(): yield from leaves(child, path+(key,))
    elif isinstance(value, list):
        for index, child in enumerate(value): yield from leaves(child, path+(index,))
    else: yield path, value


def check(key):
    release, name, expected = PINS[key]
    path = ARCH/name
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        raise ArtifactError('historical receipt SHA drift: '+name)
    value = json.loads(raw)
    original = deepcopy(value)
    def verify(trial):
        if trial != original:
            raise ArtifactError('sealed historical facts/bindings drift')
    with read_only():
        count = 0
        for route, leaf in leaves(value):
            if route[-1] == 'sha256':
                if not isinstance(leaf, str) or not re.fullmatch('[0-9a-f]{64}', leaf):
                    raise ArtifactError('invalid recorded SHA binding')
                changed = '0'*64 if leaf != '0'*64 else '1'*64
            elif type(leaf) in (int, float): changed = leaf+1
            else: continue
            trial = deepcopy(value)
            parent = trial
            for part in route[:-1]: parent = parent[part]
            parent[route[-1]] = changed
            try: verify(trial)
            except ArtifactError: count += 1
            else: raise ArtifactError('receipt numeric/SHA mutation survived')
        try: path.open('wb')
        except ArtifactError: pass
        else: raise ArtifactError('historical receipt-write survived')
        if key == 'v110':
            import c2_v110_persistent_performance as old
            old.audit_result(value)
            controls = old.mutation_proof(value)
            if controls != value['mutations_rejected']:
                raise ArtifactError('v1.10 original 22 mutations drift')
        elif key == 'completion':
            import c2_defstruct_completion_edge as old
            old.audit_result(value)
            if old.mutation_proof(value) != value['mutation_proof']['rejected']:
                raise ArtifactError('completion original 19 mutations drift')
    print(f'{key}: PASS receipt/seal only; era={release}; '
          f'numeric-and-SHA-controls={count}; rejected-write=1; '
          'original-artifact=LOST; executed-artifact-witness=NO; rebuilds=0')
    return 0
