#!/usr/bin/env python3
"""Generate and verify the fixed-capacity Workbench resident-island image."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import stat
import subprocess
import tempfile


ADDRESS = 0x1800
LIMIT = 0x2000
CAPACITY = 2048
SECTION = ".lisp65_resident_island"
START_SYMBOL = "__lisp65_resident_island_start"
END_SYMBOL = "__lisp65_resident_island_end"
CRC16_INIT = 0xFFFF
CRC16_POLY = 0x1021
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class IslandError(RuntimeError):
    pass


def _regular(path: Path, label: str, *, executable: bool = False) -> None:
    try:
        info = path.lstat()
    except OSError as exc:
        raise IslandError(f"{label} is missing or unreadable: {path}: {exc}") from exc
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise IslandError(f"{label} must be a regular, non-symlink file: {path}")
    if executable and not os.access(path, os.X_OK):
        raise IslandError(f"{label} is not executable: {path}")


def _sha256(path: Path) -> str:
    _regular(path, "ABI contract")
    value = hashlib.sha256(path.read_bytes()).hexdigest()
    if not SHA256_RE.fullmatch(value):
        raise IslandError("ABI contract SHA-256 is not canonical lowercase hex")
    return value


def _build_id(contract: Path) -> int:
    return int(_sha256(contract)[:8], 16)


def crc16(data: bytes) -> int:
    value = CRC16_INIT
    for byte in data:
        value ^= byte << 8
        for _ in range(8):
            value = (
                ((value << 1) ^ CRC16_POLY) & 0xFFFF
                if value & 0x8000
                else (value << 1) & 0xFFFF
            )
    return value


def _symbols(nm: Path, elf: Path) -> tuple[int, int]:
    _regular(nm, "llvm-nm", executable=True)
    _regular(elf, "linked ELF")
    try:
        completed = subprocess.run(
            [str(nm), "--defined-only", str(elf)],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        raise IslandError(f"llvm-nm failed: {detail.strip()}") from exc
    found: dict[str, list[int]] = {START_SYMBOL: [], END_SYMBOL: []}
    for line in completed.stdout.splitlines():
        fields = line.split()
        if len(fields) < 3 or fields[-1] not in found:
            continue
        try:
            found[fields[-1]].append(int(fields[0], 16))
        except ValueError as exc:
            raise IslandError(f"invalid llvm-nm address: {line!r}") from exc
    for name, values in found.items():
        if len(values) != 1:
            raise IslandError(f"ELF must define {name!r} exactly once, found {len(values)}")
    return found[START_SYMBOL][0], found[END_SYMBOL][0]


def _extract(elf: Path, nm: Path, objcopy: Path) -> bytes:
    start, end = _symbols(nm, elf)
    if start != ADDRESS or not start < end <= LIMIT:
        raise IslandError(
            f"resident island span is 0x{start:04x}..0x{end:04x}, "
            f"expected non-empty 0x{ADDRESS:04x}..0x{LIMIT:04x}"
        )
    if end - start > CAPACITY:
        raise IslandError(
            f"resident island has {end - start} bytes, fixed capacity is {CAPACITY}"
        )
    _regular(objcopy, "llvm-objcopy", executable=True)
    with tempfile.TemporaryDirectory(prefix="lisp65-resident-island-") as name:
        output = Path(name) / "island.bin"
        try:
            subprocess.run(
                [
                    str(objcopy), "-O", "binary", f"--only-section={SECTION}",
                    str(elf), str(output),
                ],
                check=True,
                capture_output=True,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            detail = getattr(exc, "stderr", b"")
            if isinstance(detail, bytes):
                detail = detail.decode("utf-8", "replace")
            raise IslandError(f"llvm-objcopy failed: {str(detail).strip()}") from exc
        _regular(output, "extracted resident island")
        data = output.read_bytes()
    if len(data) != end - start:
        raise IslandError(
            f"resident island ELF span has {end - start} bytes, objcopy emitted {len(data)}"
        )
    return data


def _header(*, build_id: int, data: bytes) -> bytes:
    if not 0 <= build_id <= 0xFFFFFFFF:
        raise IslandError("build ID does not fit uint32")
    if len(data) > CAPACITY:
        raise IslandError("resident island exceeds fixed header capacity")
    rows = []
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16])
        rows.append(f"    {row},")
    content = [
        "/* Generated by resident_island.py; do not edit. */",
        "#ifndef LISP65_RESIDENT_ISLAND_CONFIG_H",
        "#define LISP65_RESIDENT_ISLAND_CONFIG_H",
        "",
        f"#define LISP65_RESIDENT_ISLAND_BUILD_ID 0x{build_id:08x}UL",
        f"#define LISP65_RESIDENT_ISLAND_ADDRESS 0x{ADDRESS:04x}u",
        f"#define LISP65_RESIDENT_ISLAND_CAPACITY {CAPACITY}u",
        f"#define LISP65_RESIDENT_ISLAND_LENGTH {len(data)}u",
        f"#define LISP65_RESIDENT_ISLAND_CRC16 0x{crc16(data):04x}u",
        "#define LISP65_RESIDENT_ISLAND_BYTES { \\",
    ]
    content.extend(f"{row} \\" for row in rows)
    content.extend(["}", "", "#endif /* LISP65_RESIDENT_ISLAND_CONFIG_H */", ""])
    return "\n".join(content).encode("ascii")


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() or path.is_symlink():
        _regular(path, "existing output header")
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.tmp.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.replace(path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def prepare(args: argparse.Namespace) -> None:
    content = _header(build_id=_build_id(args.abi_contract), data=b"\x00")
    _write(args.header, content)
    print(f"resident-island-prepare: PASS capacity={CAPACITY} build_id={_build_id(args.abi_contract):08x}")


def materialize(args: argparse.Namespace) -> None:
    data = _extract(args.elf, args.nm, args.objcopy)
    content = _header(build_id=_build_id(args.abi_contract), data=data)
    _write(args.header, content)
    print(
        "resident-island-materialize: PASS "
        f"address=0x{ADDRESS:04x} length={len(data)} crc16=0x{crc16(data):04x}"
    )


def verify(args: argparse.Namespace) -> None:
    data = _extract(args.elf, args.nm, args.objcopy)
    expected = _header(build_id=_build_id(args.abi_contract), data=data)
    _regular(args.header, "resident island header")
    if args.header.read_bytes() != expected:
        raise IslandError("resident island header is stale or not the exact ELF binding")
    print(
        "resident-island-verify: PASS "
        f"address=0x{ADDRESS:04x} length={len(data)} crc16=0x{crc16(data):04x}"
    )


def selftest() -> None:
    check = b"123456789"
    if crc16(check) != 0x29B1:
        raise IslandError("CRC-16/CCITT-FALSE oracle failed")
    header = _header(build_id=0x12345678, data=b"\x01\x02\x03")
    text = header.decode("ascii")
    required = (
        "LISP65_RESIDENT_ISLAND_BUILD_ID 0x12345678UL",
        "LISP65_RESIDENT_ISLAND_ADDRESS 0x1800u",
        "LISP65_RESIDENT_ISLAND_CAPACITY 2048u",
        "LISP65_RESIDENT_ISLAND_LENGTH 3u",
        f"LISP65_RESIDENT_ISLAND_CRC16 0x{crc16(bytes((1, 2, 3))):04x}u",
    )
    if any(item not in text for item in required):
        raise IslandError("generated header contract is incomplete")
    values = re.findall(r"0x([0-9a-f]{2})(?:,| })", text.split("LISP65_RESIDENT_ISLAND_BYTES", 1)[1])
    if len(values) != 3 or bytes.fromhex("".join(values)) != b"\x01\x02\x03":
        raise IslandError("length-exact initializer is malformed")
    try:
        _header(build_id=0, data=bytes(CAPACITY + 1))
    except IslandError:
        pass
    else:
        raise IslandError("oversize mutation was accepted")
    print("resident-island-selftest: PASS (7 contracts)")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser()
    sub = result.add_subparsers(dest="command", required=True)
    sub.add_parser("selftest")
    prep = sub.add_parser("prepare")
    prep.add_argument("--abi-contract", type=Path, required=True)
    prep.add_argument("--header", type=Path, required=True)
    for name in ("materialize", "verify"):
        command = sub.add_parser(name)
        command.add_argument("--elf", type=Path, required=True)
        command.add_argument("--nm", type=Path, required=True)
        command.add_argument("--objcopy", type=Path, required=True)
        command.add_argument("--abi-contract", type=Path, required=True)
        command.add_argument("--header", type=Path, required=True)
    return result


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "selftest":
            selftest()
        elif args.command == "prepare":
            prepare(args)
        elif args.command == "materialize":
            materialize(args)
        else:
            verify(args)
    except IslandError as exc:
        print(f"resident-island: FAIL: {exc}", file=os.sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
