#!/usr/bin/env python3
"""Bind a Runtime Export Bank-5 payload to its length, CRC, and build id."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import tempfile


MAGIC = b"L65B"
VERSION = 1
TRAILER_BYTES = 12


class PreloadError(RuntimeError):
    pass


def crc16_ccitt_false(data: bytes) -> int:
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def bind(payload: bytes, build_id: int) -> bytes:
    if not payload or len(payload) > 0xFFFF - TRAILER_BYTES:
        raise PreloadError("payload length must fit a non-empty 16-bit Bank-5 span")
    if not 0 <= build_id <= 0xFFFFFFFF:
        raise PreloadError("build id must fit in 32 bits")
    trailer = bytearray(MAGIC)
    trailer.extend((VERSION, TRAILER_BYTES))
    trailer.extend(len(payload).to_bytes(2, "little"))
    trailer.extend(build_id.to_bytes(4, "little"))
    return payload + bytes(trailer)


def parse(image: bytes) -> tuple[bytes, int]:
    if len(image) <= TRAILER_BYTES:
        raise PreloadError("bound preload is truncated")
    trailer = image[-TRAILER_BYTES:]
    if trailer[:4] != MAGIC or trailer[4] != VERSION or trailer[5] != TRAILER_BYTES:
        raise PreloadError("bound preload trailer magic/version/size mismatch")
    payload_length = int.from_bytes(trailer[6:8], "little")
    if payload_length != len(image) - TRAILER_BYTES:
        raise PreloadError("bound preload trailer length mismatch")
    return image[:payload_length], int.from_bytes(trailer[8:12], "little")


def header(payload: bytes, build_id: int) -> bytes:
    crc = crc16_ccitt_false(bind(payload, build_id))
    return (
        "/* generated by runtime_export_preload.py; do not edit */\n"
        "#ifndef LISP65_RUNTIME_PRELOAD_CONTRACT_H\n"
        "#define LISP65_RUNTIME_PRELOAD_CONTRACT_H\n"
        "#define LISP65_RUNTIME_PRELOAD_PAYLOAD_BYTES %du\n"
        "#define LISP65_RUNTIME_PRELOAD_CRC16 0x%04xu\n"
        "#define LISP65_RUNTIME_PRELOAD_BUILD_ID 0x%08xUL\n"
        "#define LISP65_RUNTIME_PRELOAD_BANK 5u\n"
        "#define LISP65_RUNTIME_PRELOAD_OFF 0u\n"
        "#endif\n" % (len(payload), crc, build_id)
    ).encode("ascii")


def write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def selftest() -> None:
    payload = b"123456789"
    build_id = 0x12345678
    image = bind(payload, build_id)
    actual_payload, actual_build_id = parse(image)
    if actual_payload != payload or actual_build_id != build_id:
        raise PreloadError("roundtrip mismatch")
    if crc16_ccitt_false(payload) != 0x29B1:
        raise PreloadError("CRC-16/CCITT-FALSE oracle mismatch")
    text = header(payload, build_id).decode("ascii")
    for expected in ("PAYLOAD_BYTES 9u", "CRC16 0x66a3u", "BUILD_ID 0x12345678UL"):
        if expected not in text:
            raise PreloadError("generated header lacks %s" % expected)
    mutations = [
        image[:-1],
        image[:-TRAILER_BYTES] + b"X" + image[-TRAILER_BYTES + 1:],
        image[:-6] + b"\x08\x00" + image[-4:],
    ]
    for changed in mutations:
        try:
            parse(changed)
        except PreloadError:
            pass
        else:
            raise PreloadError("malformed bound preload was accepted")
    print("runtime-export-preload selftest: PASS payload=9 image_crc16=66a3 mutations=3")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("selftest")
    build = sub.add_parser("build")
    build.add_argument("--payload", type=Path, required=True)
    build.add_argument("--build-id", required=True)
    build.add_argument("--out", type=Path, required=True)
    build.add_argument("--header", type=Path, required=True)
    verify = sub.add_parser("verify")
    verify.add_argument("--image", type=Path, required=True)
    verify.add_argument("--payload", type=Path, required=True)
    verify.add_argument("--build-id", required=True)
    args = parser.parse_args()
    if args.command == "selftest":
        selftest()
        return 0
    build_id = int(args.build_id, 0)
    payload = args.payload.read_bytes()
    if args.command == "build":
        write(args.out, bind(payload, build_id))
        write(args.header, header(payload, build_id))
        image = bind(payload, build_id)
        print("runtime-export-preload build: PASS payload=%d image=%d image_crc16=%04x sha256=%s" %
              (len(payload), len(image), crc16_ccitt_false(image),
               hashlib.sha256(image).hexdigest()))
        return 0
    actual, actual_build_id = parse(args.image.read_bytes())
    if actual != payload or actual_build_id != build_id:
        raise PreloadError("bound preload differs from expected payload/build id")
    print("runtime-export-preload verify: PASS payload=%d build_id=0x%08x" %
          (len(payload), build_id))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, PreloadError) as exc:
        print("runtime-export-preload: FAIL: %s" % exc)
        raise SystemExit(1)
